### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by DimaMinka** [pawelgrzybek/siema#10]
I think its must have today for modern carousel.

**Comment by pawelgrzybek** [comment]
Hi.

Very good suggestion. Extremely easy to do actually (one liner). Would you like to contribute and add this feature @DimaMinka ? If now, expect it in the next update.

Thank you.

**Comment by DimaMinka** [comment]
thx for fast answer. For now i don't have a time. But after Christmas holidays i can try :) @pawelgrzybek

**Comment by pawelgrzybek** [comment]
Thanks again for reporting an issue. Expect a small patch before Christmas :)

**Comment by izebb** [comment]
@pawelgrzybek  @DimaMinka I would like to know if this enhancement have been added and how do i implement RTL.

**Comment by pawelgrzybek** [comment]
I'm still working on that. It's coming with the next version then you will get a notification @izebb . Thanks!

**Comment by LeonLiber** [comment]
Hello, thanks for doing this!
Any updates on how to do RTL? Any temporary hack?

**Comment by tvpavan** [comment]
+1

**Comment by dreamworkers** [comment]
+1

**Comment by spostad7** [comment]
+1

**Comment by pawelgrzybek** [comment]
Hi.

I'm super happy to announce that right-to-left support has been merged with master branch and it is ready to use.

https://codepen.io/pawelgrzybek/pen/XZNEgd

Thanks again for using Siema 👋
