### ISSUE TITLE
access slider object within onInit

### ISSUE THREAD

**Issue by jochemkeller** [pawelgrzybek/siema#101]
Hi there!

First of all, thanks for a great plug-in. Loving how simple and extensible the API is. I've been making some pretty amazing sliders in my projects with it.

One thing I've run across in multiple projects is that I'd like to access my slider object from within the onInit callback. If I log the object it returns undefined, however if I add a setTimeout with 100ms for instance, it logs the slider object as expected.

Please review the attached fork of your callback codepen: https://codepen.io/anon/pen/KypgeW

Any ideas? I feel dirty for using a setTimeout, was wondering if you had any pointers. 
Again, thanks for a great plug-in! Have a nice day :)

**Comment by pawelgrzybek** [comment]
Hi.

I'm very happy that you found my script useful. Definitely using setTimeout isn't needed here. If has to do with a scoping of `this` keyword when you use a arrow functions vs regular function declaration.

This will do perfectly fine :)

```js
const mySiema = new Siema({
  onInit: function() {
    onInitCallback(this)
  },
  onChange: onChangeCallback,
});
```

Have a lovely day and thanks again for using Siema!

**Comment by jochemkeller** [comment]
Ah, that makes perfect sense. Thanks so much!
