### ISSUE TITLE
<select> doesn't work anymore .... 

### ISSUE THREAD

**Issue by pociej** [pawelgrzybek/siema#102]
... if is child of slide. 

[Example](https://codepen.io/grzegorz_p/pen/bYVXvX)

**Comment by pawelgrzybek** [comment]
Hi.

Known "bug". It is going do be fixed in 1.5. Personally I wouldn't advice to put input elements inside carouse. Accessibility anti-pattern.

Thanks for reporting and have a great day 🥑

**Comment by pociej** [comment]
@pawelgrzybek thanks, unfortunately i have such carousel and trust me its not anti pattern :). 
Simple solution is just not to preventDefault in mousedownHandler, for ma case its enough.

**Comment by benjibee** [comment]
I'd like to second this issue. I think it's pretty common for carousels to have a CTA or something of the sort that users would be expected to click on, I can't see how this would be considered an _anti-pattern_ as you've stated, dear Mr. @pawelgrzybek 

[Here's a little example using Siema](https://independent-photo.com/) with a CTA that's now broken, and I'm supposed to fix 😂

**Comment by pawelgrzybek** [comment]
Hi.

Good news. This bug is fixed. I will push a solution today late on during the day.

Have a lovely Sunday pals :-*
