### ISSUE TITLE
Touch drag detection fails when delta X and Y are very small

### ISSUE THREAD

**Issue by roxlu** [pawelgrzybek/siema#105]
Hi Pawel! 

Thanks for your nice little carousel library!  

I found an issue when trying to swipe to a different slide using touch events.  In your `touchmoveHandler()` you check if the user made a horizontal or vertical movement. When the the touchstart and touchmove event are dispatched very quickly after each other the displacement in the X or Y direction is not well suited to check if you should use or skip the drag.  

I think there are two solutions to fix this; either only check in what direction the user swipped when the absolute distance is more then some number OR only check after X-millis in what direction the user swiped. I've forked your repos and pushed a fix for this second approach.

Here is the commit for the fix:
https://github.com/roxlu/siema/commit/fa9e12d41dd93066e17eca741cbda6deee6698ac

This introduces a new setting `dragDirectionCheckThreshold`.  When you set this value to e.g. 64.0 (default) we will only check if we should skip the touch session after 64.0 millis. When the touchmove rate is very high (e.g. a touchmove every 1ms) using this `dragDirectionCheckThreshold` allows the user to have some time before the touch session is actually used or cancelled.

Best regards,
roxlu

**Comment by pawelgrzybek** [comment]
Hi.

Especially for your issue I managed to buy testing  Motorola G 3rd gen for next to nothing. I will test it properly and play around with the device that doesn't dispatch events quick enough to accurately determine the swipe direction.

Personally I have never had any issues with this piece of functionality at all. I'll redo my tests this weekend. Can I be curious and ask for a device that you experienced the "problem" on?

Thanks a lot for contribution and have a lovely day @roxlu

**Comment by roxlu** [comment]
Hi, 

Wow buying a device to fix this issue: that's what I call dedication to your project! 

For this project I was using a [MultiTaction](https://www.multitaction.com/) screen. This screens sends the position of touches every X-millis (~1ms). 

Wish you a lovely day too @pawelgrzybek  :)

**Comment by pawelgrzybek** [comment]
O wow!

These hardware bu MultiTaction is looking crazy cool but let's be honest it is a very rare case. I will bare this it mind for future releases but for now I will close it down as I couldn't replicate even on old school Moto device. I will keep a mental bookmark for your commit as well.

Have a lovely weekend!
