### ISSUE TITLE
Navigation link Extra doesn't point to correct fragment

### ISSUE THREAD

**Issue by jgagne** [pawelgrzybek/siema#106]
The navigation link **8. Extra** on the [docs site](https://pawelgrzybek.com/siema/) doesn't jump to the **Extra and Thanks** section.

The link points to a fragment named `extra`, but there is no section named `extra`, instead there is a section named `extra--thanks`. (Possibly fragment and section ID name mismatch.)

**Comment by pawelgrzybek** [comment]
Thanks...
Fix to come shortly :-)
