### ISSUE TITLE
[Bug] Changing number of slides (with perPage)

### ISSUE THREAD

**Issue by ChrisPlaneta** [pawelgrzybek/siema#108]
Hi Paweł,

To keep the story short, follow these steps to reproduce the error:
1. View this Pen > https://codepen.io/kplaneta/pen/ooqJrg
2. Resize the browser's window so that 1 or 2 slides are visible
3. Go to slide 2, 3, or 4
4. Resize back to full width

What you would expect is to see 4 slides again, but the slider shows only the ones starting from the one you selected in point 3 (e.g. if you chaged slide to 2nd, you should see only 3 slides and not 4). Also, all the buttons do no work.

**Comment by pawelgrzybek** [comment]
Hi.

This is a great spot. Definitely high priority to fix.

Thanks for reporting.
