### ISSUE TITLE
[Question] Responsive per page

### ISSUE THREAD

**Issue by OwenMelbz** [pawelgrzybek/siema#11]
Love the simplicity of this after finding out about it today, however I was wondering how you'd recommend making it responsive? e.g

```
perPage 1

> 768px
perPage: 3

```

Additionally, if there is any scope for adding event listeners? e.g. changed, init etc?

**Comment by pawelgrzybek** [comment]
Hi Owen.

Really great question! I created a Codepen with temporary solution. It picks up the window resolution on load and applies correct `perPage` value. Unfortunately this one doesn't pick up the correct number of slides on windows `resize` event. This will change with the next update of Siema (I'll do my best to do it before weekend).

Link to Codepen:
http://codepen.io/pawelgrzybek/pen/LbgoVK

Thanks again for reporting an issue Owen.
Have a great day.

**Comment by OwenMelbz** [comment]
Ha yes! This was the exact first thought, I had a play with it and to use the existing version i added a resize event listener, which would delete the custom dom modifications, and re-initialised it with the new size! Obviously this is just a work around method theory, rather than an ideal solution!

But I shall be looking forward to trying the latest update out!

Thanks for the great work :)

**Comment by pawelgrzybek** [comment]
Rebuilding the whole DOM structure can be performance heavy so I would suggest to use solution that is provided on CodePen for the time being. With the new version of Siema it will just work :)

I will make the resize method debounced a bit - this will increase the performance of a whole script when the window is resized. Thanks again for reporting an issue Owen!

**Comment by OwenMelbz** [comment]
Oh yeah sure, I'm not using it in production environment, was just playing with it locally to see what it was like :)

**Comment by pawelgrzybek** [comment]
Hi Owen.

I updated Siema to provide an easy solution for your issue. Example:

```js
const mySiema = new Siema({
  perPage: {
    768: 2,
    1024: 3,
  },
});
```

Siema will default to single slide on small viewports, an on resolution wider than 768px slider layout will change to show 2 slides per page. On 1024px will show 3. Do you like it?

Have a look at example on CodePen that I updated:
http://codepen.io/pawelgrzybek/pen/LbgoVK

**Comment by OwenMelbz** [comment]
Ah lovely :D super simple :) Now just for some events haha! great work though! its definitely appreciated!
