### ISSUE TITLE
Can we make stopPropagation calls optional?

### ISSUE THREAD

**Issue by tatyshev** [pawelgrzybek/siema#110]
If somewhere in the code the following `addEventListener` is used:

```js
document.addEventListener('mousedown', () => {
  console.log('This does not work if the cursor is above the siema slider');
});
```

That event does not work when the event fires over one of the siema sliders. This is due to the fact that siema calls `stopPropagation` for some of its event handlers. Maybe it would be better to make such behavior optional?

```js
new Siema({
  stopPropagation: false
})
```

I can also do this in PR. (e8f638587a625474bd1cfb48016903d9bfd4d7a3)

**Comment by tatyshev** [comment]
@pawelgrzybek

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for reporting an issue. Can you create a CodePen example that clearly illustrated the issue please? It always helps me a lot to solve an issue or find a different solution.

Thanks and have a great day :)

**Comment by tatyshev** [comment]
Hi. Thanks for the answer.

Here is a [link](https://codepen.io/tatyshev/full/baGweK/) to the CodePen illustrating the problem, the counter does not triggered on the green box if the click fired on the siema slider.

**Comment by pawelgrzybek** [comment]
Hi my friend.

I know what is going on now. This is partially related with events propagation but there is another thing that is connected to your issue. It is not necessarily about Siema events, it is about listener declaration setup. Something that you can do is enabling capturing on your listener.

Instead of:

```js
greenBox.addEventListener('mousedown', () => {
  clicks += 1;
  counter.innerHTML = clicks;
});
```

do this…

```js
greenBox.addEventListener('mousedown', () => {
  clicks += 1;
  counter.innerHTML = clicks;
}, true);
```

Here is a fork of your codepen (the only difference is `true` to enable capturing):
https://codepen.io/pawelgrzybek/pen/WdNRVJ

Read more about capuring here:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

Hopefully it helps :-)

**Comment by tatyshev** [comment]
Yes it helped but this is true only for very simple examples. 

In our project, the `stopPropagation` behavior of siema leads to bugs of other libraries on the page, such as `Drag and Drop`, `Сustom range inputs` etc. We assumed that this behavior should not be the default.

And we don't always have the ability to change the code of third-party libraries and add `useCapture` there.

Thanks for taking time ))

**Comment by pawelgrzybek** [comment]
Can you provide an example of code where it actually cause some issue please?

**Comment by tatyshev** [comment]
Here is a small example of how can we break [@shopify/draggable](https://github.com/Shopify/draggable).

https://codepen.io/tatyshev/full/baGRgg/

Try to drag a drag element over the siema slider.

**Comment by tatyshev** [comment]
@pawelgrzybek what do you think about the previous example?
