### ISSUE TITLE
Unordered List Items as Slides?

### ISSUE THREAD

**Issue by billmakes** [pawelgrzybek/siema#112]
Hey there! I was hoping somebody could help me. Is it possible to use Siema to use an unordered list's list items as the slides instead of div's? I am having a hard time accomplishing this. I have my slider with one single slide with my list in it, rather I would like to have each item in the list as an individual slide. Any ideas?

Thank you for your time!

**Comment by pawelgrzybek** [comment]
Hi.

Of course you can you just need to clear a little bit of styling that browser applies to `ul` and `li` elements.

Solution:
https://codepen.io/pawelgrzybek/pen/PEZoXM

Thanks a ton

**Comment by billmakes** [comment]
I see thank you so much!

**Comment by pawelgrzybek** [comment]
No problem. Enjoy using Siema :)
