### ISSUE TITLE
Uncaught Error: Something wrong with your selector 😭

### ISSUE THREAD

**Issue by weevil** [pawelgrzybek/siema#114]
Howdy! I'm getting an Uncaught Error even with base usage.

`Something wrong with your selector 😭
    at new e (siema.min.js:1)
    at (index):56
`
Any ideas what I might be doing wrong?

**Comment by weevil** [comment]
I should probably add, Siema is being invoked after the js is loaded. this happens with any selector argument, but for testing I'm using a default .siema class.

**Comment by pawelgrzybek** [comment]
Hi. Thanks for reporting your issue.

Could you create CodePen example please?

Thanks.

**Comment by weevil** [comment]
ah, got it. Moved the new Siema script after my body tag close and it's happy now.

**Comment by pawelgrzybek** [comment]
Makes so much sesne :)
