### ISSUE TITLE
Pagination and text overflow into next slide

### ISSUE THREAD

**Issue by SickBit** [pawelgrzybek/siema#115]
Greetings!

First of all, thanks for providing Siema!

I'm having an issue with the pagination example you provided in your documentation.
Basically I'm testing out Siema, in terms of displaying text content instead of images. I've got it up and running, the text displays in proper pages, the divs don't overlap.
I'm currently trying to organize the supposed to display content in divs. I've found an issue that If you attempt to write long texts in slides, they will overflow to the next slide and display there. 

I'm looking into implementing a pagination feature where it displays the pages from outside of siema (a custom div where I can edit the display, style and css of the page buttons). I've managed to add a string to pagination script which adds class to the page button and allows me to modify the style. Although, the buttons instead of displaying how they display in your example ( [1][2][3][4] ), they display on the top left corner of the page that I'm currently on.
Would appreciate hearing back from you!

Thanks a lot!

Here is pagination example you've created: 
https://codepen.io/pawelgrzybek/pres/aBQxOw

Here's my codepen if that helps:
https://codepen.io/IdontCommentMyCode/pen/qpNjVq

**Comment by pawelgrzybek** [comment]
Hi.

Sorry but the example that you created and you explanation doesn't make any sense to me. The functionality that is applied to example is not relevant to your explanation and the markup is extremely easy to read.

Please show me a screenshot of a thing that you are trying to do or recreate your CodePen example just in a manner than present the issue in minimal amount of codes.

At this one I see more issues with a markup and CSS than with a Siema core by itself.

Thanks for your time and reporting a bug.
