### ISSUE TITLE
How can I build an unminified version of siema to run in the browser?

### ISSUE THREAD

**Issue by woodser** [pawelgrzybek/siema#119]
I've tried running webpack on siema.js but Siema isn't defined when it's imported.

Everything works with siema.min.js.  I'm just not sure how to browserify it.

Thanks.

**Comment by pawelgrzybek** [comment]
It has more to do with your build chain that with Siema by itself. If you a have a module bundler correctly set up to handle es2015 modules the only things that you have to is:

```js
import Siema from 'siema';
new Siema();
```

Hopefully it helped you out. Have a great day 🥑
