### ISSUE TITLE
Set delay, reset delay on interaction

### ISSUE THREAD

**Issue by thewebprojects** [pawelgrzybek/siema#122]
Hello,  

Thanks for a great piece of code.  Hopefully you can help me resolve something...

I would like each slide to be on screen for 3 seconds before automatically animating to the next slide.  I have the following code in place.  

```
new SiemaWithPagination({
	duration: 500,
	loop: true,
	onInit() {
		setInterval(() => this.next(), 3000)
		this.addPagination();
	}
})
```

You can see that I have pagination in place too. The 3 second delay appears to work if I do not flick the slide or click on a pagination button. If I flick or click the slide it doesn't seem to reset the 3 second delay and in most cases it animates to the next slide in less than 3 seconds. 

Could you provide some insight or an example that will allow it to reset the delay when a user interacts with it?

**Comment by pawelgrzybek** [comment]
Your solution isn't bad. The only thing that is missing from your code is to reset an interval whenever you interact with a pagination or navigation buttons. I'll show you a really simple code and I will challenge you to sort it out by yourself to learn a bit of useful code :)

If you wont be able to sort this out, I'll provide you a copy/pase solution, but please try to spend a bit of time to understand the concept first.

```js
// assign a variable to an interval
const myTimer = setInterval(someFunctionHere, 3000);

// ro reset an interval
clearInterval(myTimer);
```

Thanks and have a great day :)

**Comment by thewebprojects** [comment]
Thanks for the quick reply.  Hmmm... Your challenging my feeble JS skills?  The following works, but I don't know how to go to the next slide from within my 'siemaNext' function.

function siemaNext(){ alert('next slide please.'); }

const siemaTimer = setInterval(siemaNext, 4000);

```
new mySiema({
	duration: 500,
	loop: true,
	draggable: false, 
	onInit(){
		this.addPagination();
	},
	onChange(){
		clearInterval(siemaTimer);
		siemaTimer = setInterval(siemaNext, 2000);
	}
})
```

**Comment by pawelgrzybek** [comment]
```js
function siemaNext(){
  yo.next();
}

const siemaTimer = setInterval(siemaNext, 4000);

const yo = new mySiema({
	duration: 500,
	loop: true,
	draggable: false, 
	onInit(){
		this.addPagination();
	},
	onChange(){
		clearInterval(siemaTimer);
		siemaTimer = setInterval(siemaNext, 2000);
	}
})
```

:-)

**Comment by thewebprojects** [comment]
I was close.  I tried mySiema.next(); but it didn't budge.  Thanks for your time on this.  Greatly appreciated!

**Comment by thewebprojects** [comment]
Hmmm... This results with some odd behavior.  It never returns to the 1st slide after it reaches the end.  It goes back to the 2nd slide.  And the timing is still off as if it doesn't reset the interval. Drat.

**Comment by pawelgrzybek** [comment]
Can you create a CodePen for me please? At this stage I need to see the code to help you :(

**Comment by thewebprojects** [comment]
Sure. https://codepen.io/thewebprojects/pen/xpjXbg

You'll see how the slide doesn't return to "Slide One".  Also after some time the slide has a fit and begins to get twitchy.  You'll see.  Thank you very much for your input.

**Comment by pawelgrzybek** [comment]
Almost, almost :)

```js
// extend a siema class
class mySiema extends Siema {
  addPagination() {
    const navDiv = document.createElement("div");

    for (let i = 0; i < this.innerElements.length; i++) {
      const btn = document.createElement("button");
      btn.innerHTML = i;
      btn.addEventListener("click", () => {
        this.goTo(i);
        // we want to clear the interval on button click
        // not onChange callback
        clearInterval(siemaTimer);
        siemaTimer = setInterval(siemaNext, 4000);
      });
      navDiv.appendChild(btn);
    }
    this.selector.parentNode.insertBefore(navDiv, this.selector.nextSibling);
  }
}

// instantiate a new siema
const yo = new mySiema({
  duration: 500,
  loop: true,
  draggable: false,
  onInit() {
    this.addPagination();
  }
});

// callback function to setinterval
function siemaNext() {
  yo.next();
}

// start interval
// use lat because we need to reasign the value later one
// const is for constant values
let siemaTimer = setInterval(siemaNext, 4000);

```

The only difference is the moment when I reset an interval. Not onChange callback but on buton click.

Have a great day 🥑

**Comment by thewebprojects** [comment]
Perfect. Thanks again.
