### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by tridattran** [pawelgrzybek/siema#123]
An error is thrown in chrome console, when swipe is used and mobile (e.g. Galaxy S5) emulation is on.

`Unable to preventDefault inside passive event listener invocation.`

In firefox a warning is thrown, but it is essentially the same.

`Ignoring ‘preventDefault()’ call on event of type ‘touchmove’ from a listener registered as ‘passive’.`

This can be replicated using the examples in code pen: e.g. Siema basic carousel https://codepen.io/pawelgrzybek/pen/xRWEpR

**Comment by pawelgrzybek** [comment]
Hi.

Since Google Chrome introduced this "feature" this kind of error / warning showed up on majority carousel plugins. I'll sort it out at some point.

Thanks for reporting a bug. Have a great day.

**Comment by tridattran** [comment]
Cool thanks.
