### ISSUE TITLE
Center Mode Feature

### ISSUE THREAD

**Issue by yanpermana20** [pawelgrzybek/siema#125]
Hi,
This is great and very light plugin, but I don't see that Siema can do the 'Center Mode' feature. May be Center Mode can make your plugin more better.

Thanks.
![center mode](https://user-images.githubusercontent.com/2918259/34955935-570a7bfe-fa59-11e7-8663-fd40814f69f1.png)

**Comment by pawelgrzybek** [comment]
This feature require big changes to API. I discussed this feature on one of the most recent PR that I had to close because it broke more things than it fixed. Maybe in the future I'll think of this feature, but at this point this isn't possible. Sorry about it :(

**Comment by yanpermana20** [comment]
Ok, thank you. Appreciate your hard work
