### ISSUE TITLE
perPage responsive draggable issue

### ISSUE THREAD

**Issue by woodscreative** [pawelgrzybek/siema#128]
Hi, it seems in my Chrome or Safari, the `perPage` demo (https://codepen.io/pawelgrzybek/pen/dWbGyZ) items are not draggable even when `draggable` is true. Also in this previous bug issue pen (https://codepen.io/kplaneta/pen/ooqJrg) I cannot drag until I have clicked on a page number to fire the `goTo()` function in the navigation.

I used the latest version locally and have the same issue. My workaround is to call the `goTo()` method after creating the instance as `startIndex` property didn't work.

    var carousel = new Siema({
      perPage: {
        500 : 2,
        800 : 3
      },
      startIndex: 0,
      draggable: true,
      loop: true
    });
    carousel.goTo(0);

**Comment by pawelgrzybek** [comment]
Hi Paul.

Thanks for reporting. It has been fixed and sorry for this bug.

Thanks a lot for using Siema 🥑
