### ISSUE TITLE
goTo throws an error

### ISSUE THREAD

**Issue by mrdbarker** [pawelgrzybek/siema#13]
When calling `goTo` on an instantiated carousel, the method errors because `this.innerElements` is undefined (as is `this`). This is because of the lambda that is used as shown here: https://github.com/pawelgrzybek/siema/blob/4c1a2ebf50c685acb4cd7c2a6dcf3b011bba2dd9/src/siema.js#L135

Happy to fix and PR if you want?

**Comment by pawelgrzybek** [comment]
Ooo stupid me! Sorry for that! If you fancy you can, if not I will fix it in couple of hours. Thanks a ton for reporting a bug Mike!

Have a great day!

**Comment by mrdbarker** [comment]
Thanks for getting this closed so quickly!
