### ISSUE TITLE
Removing currentSlide if slide is last makes Siema slider not working anymore

### ISSUE THREAD

**Issue by creativeprogramming** [pawelgrzybek/siema#132]
To reproduce go to this Codepen:

https://codepen.io/anon/pen/mXrdgZ

Then move to last slide, and remove element, the Siema widget goes blank and you cannot swipe to previous element

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for reporting a bug, I will fix this shortly.

Thanks for using Siema 🥑

**Comment by nitronaj** [comment]
@pawelgrzybek 
on line 27
`this.currentSlide = Math.max(0, Math.min(this.config.startIndex, Math.ceil(this.innerElements.length / this.perPage)));`

**Comment by pawelgrzybek** [comment]
It is all done. The solution was fairly easy. Sorry for the bug — everything should be working just fine now.

Have a nice day and thanks again for using Siema 👋
