### ISSUE TITLE
Center mode

### ISSUE THREAD

**Issue by aczekajski** [pawelgrzybek/siema#133]
In this issue I wanted to address a matter of so-called center mode. In essence, this allows user to show currently active slide at the center of a carousel, while displaying the other slides to the left and right of the current one.  Like this:
![image](https://user-images.githubusercontent.com/3948797/34730022-892b8f56-f55e-11e7-919a-8e459e1a7b0f.png)
This is a highly common feature of other carousels.

The simplest solution that allows to achieve a center mode is to prevent Siema from applying `overflow: hidden;` to the main wrapper. I've already tried to solve it, resulting in the PR https://github.com/pawelgrzybek/siema/pull/121 which got rejected for some good reasons. There was also a solution on how to achieve different `overflow` property value which looked like this:
```js
const mySiema = new Siema({
  onInit() {
    this.selector.style.overflow = 'initial'
  }
});
```
However, this solution, while it might work, is bad in many different ways. Mainly because it uses some undocumented internals in `this` which user should not be aware of, nor should he edit them. `this.selector` might seem as a documented field because options can have a field with this name. In fact, we have completely no guarantees that options end up in `this` and, in addition, that `selector` is a DOM node, even if we passed a string as a `selector` option. This is a hack and this behavior might be broken anytime since it is not a public API.

I'm creating this issue to work together on implementing a solid solution for center mode with reliable and satisfactory API. I'll pay part of the PR which I mentioned earlier, which contains proposal of a solution:

How about: user can specify a selector or a node of inner wrapper which he could create by hand to achieve the center mode effect. Example usage:
```html
<div class="siema"> <!-- this one gets overflow hidden -->
  <div class="siema-inner"> <!-- this one gets overflow visible -->
    <!-- slides -->
  </div>
</div>
```
```js
new Siema({
  innerWrapper: '.siema-inner', //  or DOM element or true defaulting to first immediate child of '.siema'
});
```
```css
.siema {
  width: 400px;
}
.siema-inner {
  width: 100px;
  margin: 0 150px;
}
```
resulting in proper center mode.

I like this idea, since it allows you to add whatever controls/fadeouts you want inside element with `overflow: hidden`, but still having control over how many of slides are actually visible independently of their size. Or you can add even more custom wrappers if you want to.

Of course it is still just a rough idea because it needs considering more scenarios, especially with automatic width calculation and how it should behave with `perPage`. And now, of course the `innerWrapper` option doesn't even remotely suggest that it allowed you to achieve a center mode (because in fact it allows more) while I think it should.

Please consider this, having in mind that I can help with the implementation ;)

**Comment by pawelgrzybek** [comment]
Hi.

I really appreciate your effort and determination. I will repeat myself a little bit on this one. Siema has never been designed in a way that this kind of layout is achievable. The solution that I suggested with `this.selector.style.overflow = 'initial'` on `onInit()` callback is undocumented and it is a hack — obviously! If user really really wants — thats the solution, but I would use other library that has been designed with this mode in mind (Flickity or Swiper to name a few examples).

Your example works but:

- contains CSS that breaks some core rule of Siema
- we can add CSS internally but: what if device is smaller than 400px (in example provided above)?
- what if user wants to use a loop mode — it will result in flickering visible / invisible / cloned slides

There is too many things to bare in mind adding this feature, but with current implementation it will be very painful to add it to keep smooth support for remaining parts of API. It will extremely increase the size of Siema and I want to keep it simple and light. As I mentioned in some other issue, I'm more than happy to consider this feature in the future, but no earlier than next major release.

I'm more than happy to contact you directly and share with you my thoughts about Siema 2.0, future plans, and next steps and collaborate with you on adding this feature (yes, it will be smooth to add it in the future).

Thanks a lot again and have a great day.

**Comment by aczekajski** [comment]
When you leave this issue closed, I can assure you that you'll forget about ideas and help offer mentioned here. I think it'd be better idea to keep it open as and track the ideas and desires of community here. This way, by the time you begin work on 2.0, every must/should/could/won't will be probably already discussed here. But of course, I can't force it on you.

**Comment by benjibee** [comment]
I second @aczekajski's comment. I'm currently attempting to get this working, and maybe even a PR if I'm sure enough of my code, but I can't see why this issue would be closed. You're doing an awesome job, @pawelgrzybek! This isn't a demand but a request to keep it open to consideration _sometime_ in the future 😬

**Comment by tvanro** [comment]
If anyone is trying to get a center slider working in this way: **0.25 slide | 1 slide | .25 slide**
I found a way to make this work using the latest version of Siema (currently v1.5.1) by adding extra offset in the `slideToCurrent`,  `touchmoveHandler ` and `mousemoveHandler ` functions:

``` JavaScript
/**
 * Moves sliders frame to position of currently active slide
 */
Siema.prototype.slideToCurrent = function(enableTransition) {
  const currentSlide = this.config.loop ? Math.round(this.currentSlide + this.perPage) : Math.round(this.currentSlide);
  const offset = (this.config.rtl ? 1 : -1) * currentSlide * (this.selectorWidth / this.perPage) + (this.selectorWidth / (this.perPage * 4));

  if (enableTransition) {
    // This one is tricky, I know but this is a perfect explanation:
    // https://youtu.be/cCOL7MC4Pl0
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        this.enableTransition();
        this.sliderFrame.style[this.transformProperty] = `translate3d(${offset}px, 0, 0)`;
      });
    });
  }
  else {
    this.sliderFrame.style[this.transformProperty] = `translate3d(${offset}px, 0, 0)`;
  }
};

/**
 * touchmove event handler
 */
Siema.prototype.touchmoveHandler = function(e) {
  e.stopPropagation();

  if (this.drag.letItGo === null) {
    this.drag.letItGo = Math.abs(this.drag.startY - e.touches[0].pageY) < Math.abs(this.drag.startX - e.touches[0].pageX);
  }

  if (this.pointerDown && this.drag.letItGo) {
    e.preventDefault();
    this.drag.endX = e.touches[0].pageX;
    this.sliderFrame.style.webkitTransition = `all 0ms ${this.config.easing}`;
    this.sliderFrame.style.transition = `all 0ms ${this.config.easing}`;
    
    const currentSlide = this.config.loop ? Math.round(this.currentSlide + this.perPage) : Math.round(this.currentSlide);
    const currentOffset = currentSlide * (this.selectorWidth / this.perPage) - (this.selectorWidth / (this.perPage * 4));
    const dragOffset = (this.drag.endX - this.drag.startX);
    const offset = this.config.rtl ? currentOffset + dragOffset : currentOffset - dragOffset;
    this.sliderFrame.style[this.transformProperty] = `translate3d(${(this.config.rtl ? 1 : -1) * offset}px, 0, 0)`;
  }
}

/**
 * mousemove event handler
 */
Siema.prototype.mousemoveHandler = function(e) {
  e.preventDefault();
  if (this.pointerDown) {
    // if dragged element is a link
    // mark preventClick prop as a true
    // to detemine about browser redirection later on
    if (e.target.nodeName === 'A') {
      this.drag.preventClick = true;
    }

    this.drag.endX = e.pageX;
    this.selector.style.cursor = '-webkit-grabbing';
    this.sliderFrame.style.webkitTransition = `all 0ms ${this.config.easing}`;
    this.sliderFrame.style.transition = `all 0ms ${this.config.easing}`;

    const currentSlide = this.config.loop ? Math.round(this.currentSlide + this.perPage) : Math.round(this.currentSlide);
    const currentOffset = currentSlide * (this.selectorWidth / this.perPage) - (this.selectorWidth / (this.perPage * 4));
    const dragOffset = (this.drag.endX - this.drag.startX);
    const offset = this.config.rtl ? currentOffset + dragOffset : currentOffset - dragOffset;
    this.sliderFrame.style[this.transformProperty] = `translate3d(${(this.config.rtl ? 1 : -1) * offset}px, 0, 0)`;
  }
}
```

Then initialize a Siema slider that has 1.5 slides per page:
``` JavaScript
new Siema({
  perPage: 1.5,
});
```

**Comment by pawelgrzybek** [comment]
Hi.

I have to admit this is an interesting example. It is such a cool feeling to design some API and see how developers use it in creative way.

Have a nice day 👋
