### ISSUE TITLE
Vue plugin 

### ISSUE THREAD

**Issue by sainf** [pawelgrzybek/siema#135]
Hi.

Thanks for the great work!

I'm using nuxt/vue and I saw that the plugin by Marko Bolliger was old, so I write a new plugin to wrap this great library.

https://github.com/sainf/vue2-siema

**Comment by pawelgrzybek** [comment]
WOW! Thanks!

I will let you play around with it and test it (if you don't mind because I don't know Vue really well) and I'm more than happy to update Siema website with your lib.

Thanks a lot ‼️‼️‼️

**Comment by pawelgrzybek** [comment]
Thanks again for your contribution! I'll be really thankful if you could keep your repo in sync with a current Siema API. Don't worry, I don't expect any big changes anytime soon, maybe some tiny performance optimisations but not a challenging implementation at all :)

**Comment by sainf** [comment]
Sure, I'll try to use only your script in all slider/carousel.
Thanks for the attention and all the work done in this very lightweight library!
