### ISSUE TITLE
Suggestion - move touch stuff into seperate dependency

### ISSUE THREAD

**Issue by garygreen** [pawelgrzybek/siema#136]
It would be cool if all the "touch" related options / functionality was moved into it's own separate `touch.js` file or something - that way you can tree shake it away with Webpack if you don't need it. E.g. your simply not using that functionality, or you have another library like Swipe.js to do touch related stuff.

Same kind of principle could apply to other options, like have a `responsive.js`. Some people might not need a responsive caroursel, so having ability to tree shake / remove certain modules from within your package bundler would be awesome.

I think that's the problem with other carousel libraries is they are so monolith in their setup - it's either a all or nothing type approach. So people contribute stuff and it keeps on growing and growing - with a more modular design you can pick - "Ok, I want a responsive, non-autoplaying carousel, don't need drag related stuff" and you could have a very simple carousel package that is only 1kb and does exactly what you want.

**Comment by pawelgrzybek** [comment]
Hi.

This is a great idea and I am planing to release this kind of separation very soon (probably next major release). It comes with few disadvantages that I'm more than happy to share with you…

**1. Less advanced users**

Not everyone is using module bundlers. I get tons of "how to" questions from less advanced users who are familiar with HTML and CSS only. Less advanced developers is currently a perfect target for Siema as it doesn't require a configuration almost at all. Even the video tutorial aims to explain the Siema implementation to users with basic skills only.

**2. It is not that heavy.**

Currently Siema is about 3kb which makes it by far the lightest carousel solution on the market. I think that at this point I found a great compromise between features that should live in a core as a single lib and some extras that may be potentially enclosed in a separated module. I really like your idea about splitting few things into separated modules and I am going to do so. I am not going to split a configurable logic into separated modules tho. Frequently requested features like navigation buttons or pagination with dots will go to separated modules and I am going to develop official tiny addons for that soon.

Thanks for a great idea. Hopefully you get my reasoning and you found my compromise fair :)
