### ISSUE TITLE
No fail-safe for carousel with loop enabled and fewer carousel items than perPage value

### ISSUE THREAD

**Issue by gempi** [pawelgrzybek/siema#137]
Hi - there is an error if `loop` is enabled and there are fewer carousel items than the `perPage` value is.

```
Uncaught TypeError: Cannot read property 'cloneNode' of undefined
```

Error is showing up since Siema v1.5.0. Check this example:
https://codepen.io/gempi/pen/ddezQg

**Comment by pawelgrzybek** [comment]
Hi.

I am aware of this bug. I will fix it in a next release. Thanks for using Siema @gempi 

Thanks for contribution and have a great day 👋

**Comment by gempi** [comment]
Thanks for your quick response and this great project!

**Comment by modwebpl** [comment]
Well, I was do like this:

_setVars: function (el) {
    var _this = this;

    _this._slider = el;
    if (!_this._slider) return;

    _this._slideCount = _this._slider.children.length;

    return true;
  },

  _setEvents: function () {
    var _this = this;

    if(_this._slideCount >= 2) _this.slider();  // stop carousel when only 1 items
  },

**Comment by sam11385** [comment]
I have spotted this error as well. 

@gempi do you get the error when using your local version of your code? I do not, I only have the error on the server.

**Comment by gempi** [comment]
@sam11385 I'm always getting the error with my config (see codepen). As @pawelgrzybek mentioned, it's seems to be a known bug.

**Comment by arnayak4u** [comment]
We are planning on using this for our project. @pawelgrzybek  , Could you please let us know when can we expect this bug to fixed?

**Comment by pawelgrzybek** [comment]
Hi.

I will ask you all one question. Not that I am trying to explain myself here, because this is definitely my fault and my poor testing introduce this bug, but...

Why would you like to use a multiple slider per page if you don't have enough slides to fill the whole width of a container? Logically, the main purpose of using pagination is to reduce gragging if you have tons of elements. Why would you like to use it if you have fewer slides than can possibly fir on a page?

Have a great one y'all! 👋

**Comment by sam11385** [comment]
For our purpose, we have the slider for multiple images. Occasionally though, a user has less than the slider's set number of images. We combated the issue with an ngIf in the template.

**Comment by antony** [comment]
Another fix for this (in-app) if you're using responsive page counts:

```js
  const perPage = {
    820: Math.min(adventures.length, 2),
    1240: Math.min(adventures.length, 3)
  }
```

**Comment by simplenotezy** [comment]
Any updated on this bug? Do you still need help fixing this issue? @pawelgrzybek

**Comment by simplenotezy** [comment]
It also happens if you display 4 items perPage, but only have 7 items in the slider.

**Comment by antony** [comment]
@simplenotezy @pawelgrzybek is no longer maintaining siema. If you want this issue to be fixed, I'd suggest fixing it yourself and opening a PR. There is a chance it might get merged.

**Comment by Acidic9** [comment]
Simple solution:

Eg: 4 per page
```js
new Siema({
  perPage: Math.min(4, totalSlides),
});
```
