### ISSUE TITLE
"Siema - auto play & loop" CodePen example fast-forwards when change tab and go back in Chrome

### ISSUE THREAD

**Issue by Javi-er** [pawelgrzybek/siema#138]
I need to have a carousel that auto plays constantly (like the example) but when I switch from tab and go back, it moves forward like crazy. This is probably because setTimeout() functions stack when you aren't on the tab, do you know any solution for this? I tried with:

```
$(window).blur(function() { stopInterval })
$(window).focus(function() { startInterval })
```
But it doesn't really work since if you click the address bar it loses the focus and it stops, also if you scroll the page it doesn't regain it, so you end up with the slider frozen in some situations.

https://codepen.io/pawelgrzybek/pen/MbPbLM

**Comment by pawelgrzybek** [comment]
Hi.

My example show just a simple and most basic usage of API. The implementation is up to the user. I have a two news here — one bad and one good.

Bad — it looks strange obviously.

Good — it is a correct functionality and it is not related with Siema but more wieth a browser internals and my dirty API usage.

There is a thing called [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) and it emits an event called `visibilitychange` on document object whenever the tab changes its state. This is one is my best bet to use in connection with `setInterval()` and Siema. Essentially when you leave tab with auto looping Siema, the counter is counting but the transitions and all the animations on the page are stopped from obvious performance gain reasons. Whet user comes back to a tab with Siema, transitions and animations are catching up.

Hopefully this explanation helps. Thanks and have a great day :)

**Comment by Javi-er** [comment]
Thanks for the quick answer! it looks like the page visibility api should take care of this issue, I'll try it.
