### ISSUE TITLE
2 Features/PRs propositions : slideshow & bullets

### ISSUE THREAD

**Issue by pandaiolo** [pawelgrzybek/siema#14]
Hi there, I'm planing to use siema and I will add for my project 2 capabilities to it : 

1. Slideshow feature. It could be a `slideshowDelay` in the config, expressed in milliseconds, defaulting to `0` (disabled). When enabled it would just go through the slides automatically.

2. Bullets indicators _à la_ Apple : `bulletMarks` in the config, default to `false`, would display a bullet ASCII character for each slide. If `true`, default colors would apply, With providing an object as the value instead, with `active` and `inactive` props, for example, with RGBA values, those customs colors would apply.

I can either add these features in my app, or add one or both to your component and propose a PR.

Tell me if it's something you're interested in !

BTW Thanks for this OSS component :-)

**Comment by pawelgrzybek** [comment]
Hi Aurelien.

To be honest I like is as it is without navigation or bullet points that are built into prototype. I would love to keep it this way. Slideshow is another functionality that can be done with few lines of code. I would love to challenge users to use a little bit of js not just drop in a script that does everything :)

The example of very easy slideshow is inside the CodePen collection. Have a look:
http://codepen.io/pawelgrzybek/pen/MbPbLM

For the time being lets keep it as it is without adding those features to app please. When you finish your project I would love to see you what you build with Siema Aurelien.

Have a great day 😊

**Comment by pandaiolo** [comment]
Sure, thanks for the quick answer !
