### ISSUE TITLE
TypeError: Siema is not a constructor

### ISSUE THREAD

**Issue by ab18556** [pawelgrzybek/siema#143]
I installed the latest release of  Siema (1.5.1) like this:
`yarn add siema`

When I try this:
```
import Siema from 'siema';
new Siema();
```
I get this error message
`TypeError: Siema is not a constructor`

I also noticed that the npm package does not contain any sources.

**Comment by pawelgrzybek** [comment]
Hi.

there must be something wrong with your package manager. I replicated your steps and created the easiest version of Siema possible:

```
yarn init
```

```
yarn add siema
```

then markup:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

  <div class="siema">
    <p>Lorem ipsum dolor sit amet consectetur.</p>
    <p>Lorem ipsum dolor sit amet consectetur.</p>
  </div>

  <script src="./node_modules/siema/dist/siema.min.js"></script>
  <script>
    new Siema();
  </script>
</body>
</html>
```

Everything is working as expected to me Sir. Please make sure that your yarn / npm is woking properly.

Thanks

**Comment by ab18556** [comment]
Oh, but you are including the script directly in a script tag.
I was importing as a module like this:
```
import Siema from 'siema';
new Siema();
```
Could this be the issue?

**Comment by pawelgrzybek** [comment]
I doubt it. It is doing the same thing in a background.

**Comment by spsaucier** [comment]
I'm having the same issue when importing as @ab18556 had.

**Comment by TobiasMalikowski** [comment]
I'm having the same issue while using Siema with Angular.

`
import Siema from 'siema';
new Siema()
`
Result: ERROR TypeError: siema_1.default is not a constructor

**Comment by davidcort** [comment]
I'm having the same issue when importing as @ab18556 had.

I am using gulp. I try this:

`import Siema from 'siema';

export default class Swiper {
    constructor(){
        //Init Slider
        const siemaSlide = new Siema({
            selector: '.swiper-wrapper',
            duration: 200,
            easing: 'ease-out',
            perPage: 3,
            startIndex: 0,
            draggable: true,
            multipleDrag: true,
            threshold: 20,
            loop: false,
            rtl: false
        });
    
        //Prev and Next buttons
        document.querySelector('.swiper-button-prev').addEventListener('click', () => siemaSlide.prev());
        document.querySelector('.swiper-button-next').addEventListener('click', () => siemaSlide.next());
    }
}`

The result is:

Uncaught TypeError: Swiper is not a constructor

**Comment by pawelgrzybek** [comment]
You both just have some issue with execution order.

**Comment by melanie-idl** [comment]
Having the same issue currently with v1.5.1 `const { Siema } = require('siema');`
```
const options = {
  draggable: true,
  loop: true,
  duration: 400,
  multipleDrag: false,
  perPage: 4,
};

this.siema = new Siema({
  selector: inner,
  options,
});
```

**Comment by pedelman** [comment]
I was able to get past this issue using the following import syntax.

```ts
import Siema = require('siema');
// doesnt work: import Siema from 'siema';
import { someOtherImport } from './util/something'
...
```

```ts
this.siema = new Siema();
```

No longer raises: `Uncaught TypeError: n.default is not a constructor`
