### ISSUE TITLE
Support IE10 but const/let contains in source siema.js

### ISSUE THREAD

**Issue by NikolaySolodukhin** [pawelgrzybek/siema#144]
Hi. I am sure that something will go wrong in the ie10, because in siema.js contains variables const and let IE 10 doesn't support it. Only ie 11 https://caniuse.com/#search=const

**Comment by pawelgrzybek** [comment]
Hi.

I use ECMAScript 2015 (and above) features on Siema heavily but everything is compiled to code that runs smoothly on Internet Explorer 10 via Babel.

https://github.com/pawelgrzybek/siema/blob/master/webpack.config.js#L21-L29

If you have a look at the generated output that is delivered to the end user you wont find any let / const and other ES2015 features.

https://raw.githubusercontent.com/pawelgrzybek/siema/master/dist/siema.min.js

Have a nice day :)
