### ISSUE TITLE
Multiple instances of Siema on a page with autoplay and prev/next buttons 

### ISSUE THREAD

**Issue by Gumbino** [pawelgrzybek/siema#145]
Hello, I really like Siema. It's so small and works very well. I am having trouble trying to combine two of the examples so that I can have two Siemas on the same page, with both having autoplay and having prev/next buttons.

I have tried to combine these two examples, but I can't get it to work:

https://codepen.io/pawelgrzybek/pen/JbaELp
https://codepen.io/pawelgrzybek/pen/MbPbLM

What is the correct way of combining them?

Thanks so much.

**Comment by pawelgrzybek** [comment]
Hi.

I created a CodePen for you. Each line in JS section is commented out to let you better understand the concept. Hopefully this is helpful.

https://codepen.io/pawelgrzybek/pen/qoRxzV

Thanks for using Siema and have a lovely day 👋

**Comment by Gumbino** [comment]
Thanks, that is great. How would I add the previous and next buttons to these?

**Comment by Gumbino** [comment]
Thanks, that is great. How would I add the previous and next buttons to these?

**Comment by pawelgrzybek** [comment]
> Thanks, that is great. How would I add the previous and next buttons to these?

There is a great example on a CodePen collection.

**Comment by lucvanloon** [comment]
I was looking for an example to get multiple siemas to work with buttons. Using your example I was able to do so. Probably not the prettiest, but it works for anyone looking:
https://codepen.io/lucvanloon/pen/zaRZwJ
