### ISSUE TITLE
Callbacks triggering

### ISSUE THREAD

**Issue by SteppeEagle** [pawelgrzybek/siema#146]
Hi
Callbacks for methods **prev** and **next** and callback **onChange** trigger immediately but they should trigger after animation will finish.

**Comment by pawelgrzybek** [comment]
Hi.

Debatable. Current implementation triggers callback when slides changes. It seems to be intuitive. I may add some addition global feedback for `transitionend` but I don'tfeel a strong need of doing that now :)

Thanks
