### ISSUE TITLE
Sliding in reverse with multiple images per page.

### ISSUE THREAD

**Issue by morgantaylor193** [pawelgrzybek/siema#150]
Hey, 

I have my gallery set up with 5 images displayed per page. When I click image 2 it moves it to position 1 and then image 6 to position 5. This continues until the last image comes into view. This is awesome however when I then click on the image in position 1 it does not slide the previous image back into view. Is there a way in which this could be achieved?

Thanks in advance

**Comment by pawelgrzybek** [comment]
Hi.

CodePen / JSbin / JSfiddle example please please please please please please!

Thanks in advance :)

**Comment by morgantaylor193** [comment]
https://codepen.io/morganTaylor193/pen/PRoGbb

**Comment by pawelgrzybek** [comment]
I am really sorry but I still do not understand the issue.  Looking at this code and implementation everything is looking perfectly fine to me.
