### ISSUE TITLE
Center mode for odd number of slides

### ISSUE THREAD

**Issue by EricSSartorius** [pawelgrzybek/siema#152]
Loving this carousel as it is light and still has lots of features! 

Was wondering if there is ever any plans for adding a center feature where the current slide would be in the center as opposed to the far left. (This would work well with an odd number of slides).

Thanks!

**Comment by pawelgrzybek** [comment]
Hi.

There was a conversation about it and I will do it in next big release of Siema. It will be 2.0. It will introduce few breaking changes and few new features, it will be even lighter, written entirely in TypeScript with full e2e test.

Unfortunately you have to wait for it a little bit :(

Thanks and have a great day 👋
