### ISSUE TITLE
Wrong dots pagination with custom "perPage" option

### ISSUE THREAD

**Issue by modwebpl** [pawelgrzybek/siema#153]
Hello,

I found on the internet your solution wich improve Siema slider by a new option: "dots pagination". Well it's a great idea but something weird is happen when we change the custom option "perPage" for example from 1 to 2 :)

Example here: https://codepen.io/modweb_pl/pen/PReYvx

Do you know how to solve this issue?
Maybe you have an a aditional method which properly calculate the numbers of dots for more then one slider per page?

**Comment by pawelgrzybek** [comment]
Hi.

Technically there is nothing wrong about this example. You are showing two slides, so two dots should be highlighted in this case. There is ore an issue with an "improved version of Siema" in this case.

Hopefully my reasoning makes sense to you Paweł (cool name by the way).

Have a great Easter 👋

**Comment by hibikikudo** [comment]
@modwebpl add little change in updateDots function https://codepen.io/h_kudo/pen/QPBbOd
