### ISSUE TITLE
Images are missing in your codepen examples.

### ISSUE THREAD

**Issue by Chrisedmo** [pawelgrzybek/siema#155]
Just tried to look at the codepen examples and all the images are missing, so the slides do not work.

**Comment by pawelgrzybek** [comment]
Great point. it is all related with changing a hosting and platform of my personal website. Sorry about it, and I will fix it asap.

**Comment by pawelgrzybek** [comment]
Everything should be back to normal. Sorry!

https://github.com/pawelgrzybek/pawelgrzybek.com/commit/4fec4b626f34884bf3bff3b35d8279681df17091
