### ISSUE TITLE
Events memory leak

### ISSUE THREAD

**Issue by pandaiolo** [pawelgrzybek/siema#16]
The component subscribes to many events behind the scene, and does not seem to unsubscribe later on. The events on the carousel element itself, should be taken care of in modern browser, when they are discarded, but there is a `resize` event on the `window` element, and it is an anonymous function, so I don't see any way to unsubscribe the event later. Any advice ?

**Comment by pandaiolo** [comment]
I think this could be avoided without overhead by putting the event code in an instance method, which could be then unsubscribed manually on those scenarii

**Comment by pawelgrzybek** [comment]
This is one of those scenarios where you need to find a compromise between simplicity and performance. I agree `resize` put on the window object is one of the nastiest things that you can do, but on UI components sometimes that is the only option.

Do you have any idea what to do about it? Would you like to contribute? Do you really notice any consequences of leaking memory on your project? Do you have any experience how other libraries handle it?

**Comment by pawelgrzybek** [comment]
And really thank you for active contribution on my project. Really appreciate it!

**Comment by pandaiolo** [comment]
I made a PR with my idea about it, because it's not a lot of code. Feel free test & use. Im my case I end up using another thing that is more relevant for a React app.

**Comment by Hagith** [comment]
@pandaiolo can you share what you've used for React app? we also looking for some light slider to use in SPA powered by Vue.js

**Comment by pandaiolo** [comment]
@Hagith I ended up using a reat-ready component: https://github.com/amio/re-carousel

**Comment by Kaveckas** [comment]
I've tried to make a port of Siema to React myself, check it out - https://github.com/Kaveckas/react-siema

**Comment by pawelgrzybek** [comment]
@Kaveckas I will give it a go and add to your website if you don't mind. Thanks for contribution mate!

**Comment by cannap** [comment]
awesome slider i work on a vue version but still not vue enough for release 🍡  
https://github.com/cannap/vue-siema

**Comment by pawelgrzybek** [comment]
Thanks a agin for your help. I added `destroy()` method to version 1.1.0. There is an use example inside Codepen collection:

http://codepen.io/pawelgrzybek/pen/ZLpbqy

Thanks again 👊
