### ISSUE TITLE
Trying to hide previous and next button on 

### ISSUE THREAD

**Issue by reachdevelopers** [pawelgrzybek/siema#163]
does anyone knows how to hide the previous button when the first slide is visible, also vice-versa when the last slide is visible hide next button.  I have this per page setup 
`                perPage: {
                    576: 1,
                    768: 2,
                    1200: 4
                }`

**Comment by pawelgrzybek** [comment]
Hi.

Quick and dirty but it is working. you get what its going on :)

https://codepen.io/pawelgrzybek/pen/OZLyEv

Thanks and have a nice day 👋

**Comment by reachdevelopers** [comment]
work nice! except when I resize the browser screen.

**Comment by pawelgrzybek** [comment]
Attach the same callback to onResize and you are good mate :)

**Comment by reachdevelopers** [comment]
where do I add this onResize
