### ISSUE TITLE
Add next / previous button to multiple carousel

### ISSUE THREAD

**Issue by willstar22** [pawelgrzybek/siema#164]
It is possible to add next/previous button to multiple carousel?  I have two carousel running on the same page but could not work out how to add next/previous buttons to each carousel. It is possible to achieve? 

William

**Comment by pawelgrzybek** [comment]
Hi.

You have to edit constructor class for it. There is a copy and paste example on CodePen collection.

Thanks and have a great day 👋

**Comment by willstar22** [comment]
Sorry for my limit knowledge working with javascript. Could you mind show me show it works?

**Comment by willstar22** [comment]
Thank you for the codepen sample. Much appreciated.

**Comment by willstar22** [comment]
I add it inside tabs-panel (Foundation Tab) and when I clicked tab 2 the slider does not show up but when click back to Tab One works. Any ideas what cause the slider's disappearance in Tab Two?

**Comment by pawelgrzybek** [comment]
Without c CodePen example I am helpless. I don't have enough context :(
