### ISSUE TITLE
The prev and next buttons do not work querySelectorAll

### ISSUE THREAD

**Issue by paveell** [pawelgrzybek/siema#165]
good afternoon

The buttons for prev and next do not work, tell me how to activate them.

I use several sliders on the page
  
```
const siemas = document.querySelectorAll('.swip');

for(const siema of siemas) {
  new Siema({
    selector: siema,
	//duration: 200,
	threshold: 200,
	easing: 'ease-out',
	//perPage: 1,
	startIndex: 0,
	draggable: true,
	multipleDrag: true,
	threshold: 20,
	loop: false,
	rtl: false,
	onInit: () => {},
	onChange: () => {},
  })
}
```

     <div class="swiper">
			
     <button class="swiper__btn-prev" type="button"></button>
						
	<div class="swiper__container swip">
		  	  <div class="swiper__wr service__iner">
		  	  	
		  	  	<a class="swiper__slide service__item slide-prev" href="#">
		  	  	    <i class="service__icon service__icon--general"></i>
		  	  	    <p class="service__name">Генеральная</p>
		  	  	</a>
		  	  	
		  	  	<a class="swiper__slide service__item slide-active" href="#">
		  	  		<i class="service__icon service__icon--repair"></i>
		  	  		<p class="service__name">После ремонта</p>
		  	  	</a>

		  	  </div>
            <span class="swiper__notification" aria-live="assertive" aria-atomic="true"></span>
		  </div>				
				
		<button class="swiper__btn-next" type="button"></button>				
	</div>

It is necessary to use the buttons:

```
<button class="swiper__btn-prev" type="button"></button>
<button class="swiper__btn-next" type="button"></button>
```

The options I applied did not help in solving this problem:

```
const prev = document.querySelector('.swiper__btn-prev');
const next = document.querySelector('.swiper__btn-next');

prev.addEventListener('click', () => mySiema.prev(3));
next.addEventListener('click', () => mySiema.next(3));
```

[https://codepen.io/pawelgrzybek/pen/yVxmEp](https://codepen.io/pawelgrzybek/pen/yVxmEp)

Thank you.

**Comment by pawelgrzybek** [comment]
Hi.

There is a copy and paste solution for this issue on CodePen collection. You must be doing something wrong in your implementation that is not related with Siema. Sorry for being helpless in this case.

Thanks a lot and have a great day 👋

**Comment by paveell** [comment]
I have reviewed all the examples that are, I have not found a solution to this problem.
