### ISSUE TITLE
pagination disappears when resizing screen

### ISSUE THREAD

**Issue by mvhoute** [pawelgrzybek/siema#169]
Hi Pawel, 

I really enjoy using Siema, we've already had a lot of implementations using this library. But.. I found a bug. 

I've used your example 'add pagination to prototype' just like the example on Codepen https://codepen.io/pawelgrzybek/pen/aBQxOw. However, if you slightly change the screen dimensions, the buttons completely disappear from the DOM tree. I noticed it when I closed / opened the code inspector in my browser. It's also happening in your Codepen example, so I don't think it's necessary to include a jsFiddle. 

I really hope you can provide a solution for this bug. Thanks in advance!

**Comment by pawelgrzybek** [comment]
Hi.

Sure thing that i will help. because it is not part of APi it is required to handle case like this yourself. Solution is easy :)

```js
// Siema doesn't come with pagination built in
// But it is very easy to add one if you want

// New siema instance
const mySiema = new Siema();

// Add a function that generates pagination to prototype
Siema.prototype.addPagination = function() {
  for (let i = 0; i < this.innerElements.length; i++) {
    const btn = document.createElement('button');
    btn.textContent = i;
    btn.addEventListener('click', () => this.goTo(i));
    this.selector.appendChild(btn);
  }
}

// Trigger pagination creator
mySiema.addPagination();

// Trigger pagination on window resize
window.addEventListener('resize', () => mySiema.addPagination())
```

Thanks and have a nice weekend :)

**Comment by mvhoute** [comment]
Thank you @pawelgrzybek, the solutions was really easy. I almost feel ashamed for asking ;-)
