### ISSUE TITLE
Different duration between click and drag

### ISSUE THREAD

**Issue by Loykos** [pawelgrzybek/siema#172]
Hi,

I'm very happy with siema library but I have a problem in this use case.

I'd like to insert a carousel with next/prev button to switch photo instantly (0 duration) and also allowing dragging. I've set duration to 0 and draggable to true but when I release a photo (after start dragging) the photo switch instantly (due to the 0 duration) but looks like a strange behaviour to the user.

I think it would be nice to separate duration for click (es. next/prev buttons) and drag or set always a smooth animation on release.

**Comment by pawelgrzybek** [comment]
Hi.

Technically this is a expected and correct behaviour but I get it may be frustrating in your case. It requires some code manipulations. Unfortunately I consider it as an edge case and you a first user who requested something like that. It would require big changes in API to split duration for two events and it is not worth it for such a rare situation.

Sorry for that. Unfortunately there is no simple solution to extends a Siema class for your issue and I doubt I will add it anytime soon.

Thanks for contribution anyway 👋

**Comment by Loykos** [comment]
Thanks for your answer. I solved this problem with a workaround. I post the code to help someone else need this feature. I set duration to 200 and then I disable the duration when click next/prev button:

` this.nextArrow.addEventListener('click', () => {
            this.config.duration = 0;
            this.disableTransition();
            this.next(1, function () {
                let configs = this.config;
                setTimeout(function () {
                    configs.duration = 200; // Initial duration value
                }, 50);
            });
        });`

But I not it's not a clean solution. I use this code with loop = true. I inserted a "setTimeout" function because the callback in the next() API method is fired before the slide transition completes.
