### ISSUE TITLE
Visual hint

### ISSUE THREAD

**Issue by brasilikum** [pawelgrzybek/siema#173]
First off: Thank you so much for this lib, it is very helpful.

I was looking for a way to have a subtile hint that the element in fact is a gallery and not just an image.
Of course I could implement hovering buttons, but they is often in the way of things.

It would be cool to have something similar to the easing function that can be played after init that has the same effect then someone dragging the first slide a little and then letting go.

Something like this, just in the opposite direction.

![](http://g.recordit.co/Wzcpqca1Qd.gif)

I tried to implement something but I feel like this touches the internal logic and maybe you see this as a useful feature to many users.

If not, maybe you have a suggestion where I can start.

Cheers!

**Comment by pawelgrzybek** [comment]
Hi.

Your idea maybe suits your current project but it is definitely not a thing that I will consider adding to a Siema core. If I was you, I would consider some very basic "hint" animation via simple CSS to achieve this effect.

Let me know what you ended up doing. Thanks a lot for contribution 👋
