### ISSUE TITLE
New option — vertical sliding?

### ISSUE THREAD

**Issue by fbnntt** [pawelgrzybek/siema#179]
Hello,

I've recently used Siema for the first time and it's been brilliant!

I was wondering if you've ever thought of having a vertical sliding option for the carousel?

**Comment by pawelgrzybek** [comment]
Hi.

The whole point of carousel is to make some elements draggable / slidable in an opposite orientation than the natural scrolling on the platform.  I consider vertical scrolling an anti-pattern and in majority of cases it would be harmful for UX (even horizontal carousels are to be honest with you).

I am not planing to implement vertical scrolling to Siema. Hopefully y reasoning makes sense to you.

Thanks for contribution and have a great day 👋

**Comment by bennkingy** [comment]
@pawelgrzybek Their are lots of use cases where you need vertically scrolling :(

**Comment by pawelgrzybek** [comment]
Can you give me one good valid use case where you need a vertical scrolling but you don't harm accessibility at the same time?

**Comment by iquinones-bsale** [comment]
thumbnails for example. a slider with vertical thumbnails

**Comment by dkochetkov** [comment]
> Can you give me one good valid use case where you need a vertical scrolling but you don't harm accessibility at the same time?

I really need to scroll that carousel vertically with pinned left column and carousel navigation dots:

<img width="826" alt="Снимок экрана 2020-05-22 в 18 23 20" src="https://user-images.githubusercontent.com/20298318/82683233-5b89c780-9c59-11ea-8cc5-9b3756d63fdc.png">

**Comment by pawelgrzybek** [comment]
Hi @dkochetkov. 

I am almost sure that you can use CSS scroll snap for things like this in 2020. For your use case, if it is not supported it doesn't break functionality at all. If it does it is a perfect progressive enhancement. Carousel is not meant to be used for things like this.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap

Have a great weekend dude and thanks for your comment.

**Comment by dkochetkov** [comment]
> Hi @dkochetkov.
> 
> I am almost sure that you can use CSS scroll snap for things like this in 2020. For your use case, if it is not supported it doesn't break functionality at all. If it does it is a perfect progressive enhancement. Carousel is not meant to be used for things like this.
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap
> 
> Have a great weekend dude and thanks for your comment.

Thanks for this great idea!
I will check the possibility of using this approach within the project .
