### ISSUE TITLE
this.goTo(i) is not a function

### ISSUE THREAD

**Issue by ilyagru** [pawelgrzybek/siema#18]
Dzień dobry!

I have an error (Uncaught TypeError: this.goTo is not a function
    at HTMLAnchorElement.<anonymous>) when adding pagination. What is the problem? Also a question: Should buttons be in .case-slider div?

```
$(function() {
    var caseSlider = new Siema({
        selector: '.case-slider',
        perPage: 1,
        startIndex: 0,
        draggable: false,
    });
    $('.case-slider-prev').click(function() {
        caseSlider.prev();
    });
    $('.case-slider-next').click(function() {
        caseSlider.next();
    });

    Siema.prototype.addPagination = function() {
        var buttons = $('#similar-projects a');
        for (var i = 0; i < this.innerElements.length; i++) {
            var btn = buttons[i];
            btn.addEventListener('click', function() {
                this.goTo(i);
            });
        }
    }

    // Trigger pagination creator
    caseSlider.addPagination();
});
```

**Comment by pawelgrzybek** [comment]
O cześć :)

I see where the problem is. You swapped arrow function with regular function expression. `this` keyword works a bit differently inside these two. Arrow function fetches scope it sits inside so `this` with arrow function resolves to instance of Siema. When you use `this` inside regular function expression `this` resolves to clicked element. `goTo()` method is property of a Siema, not of a clicked button. Fortunately there is easy fix my friend :)

```js
$(function() {
    // You don't have to repeat default values in setting object
    // I removed perPage and startIndex
    var caseSlider = new Siema({
        selector: '.case-slider',
        draggable: false,
    });
    $('.case-slider-prev').click(function() {
        caseSlider.prev();
    });
    $('.case-slider-next').click(function() {
        caseSlider.next();
    });

    Siema.prototype.addPagination = function() {
        var buttons = $('#similar-projects a');
        var self = this;
        for (var i = 0; i < this.innerElements.length; i++) {
            var btn = buttons[i];
            btn.addEventListener('click', function() {
                self.goTo(i);
            });
        }
    }

    // Trigger pagination creator
    caseSlider.addPagination();
});
```

I know it is confusing a bit. I have a great resource for you. It helped me so maybe you will find it helpful as well.

[ES6 arrow functions, syntax and lexical scoping by Todd Motto](https://toddmotto.com/es6-arrow-functions-syntaxes-and-lexical-scoping/)

Buttons can be wherever you want. As long as you know where they are it is fine :)

**Comment by ilyagru** [comment]
Oh, thank you very much. But now I have this `Uncaught TypeError: Cannot read property 'innerElements' of undefined
    at e.goTo (siema.min.js:1)`

**Comment by pawelgrzybek** [comment]
Can you make a quick CodePen / jsFiddle /  please?

**Comment by ilyagru** [comment]
I am working on a complicated block but I have tried to simplify it for fiddle. There is an error also.
https://jsfiddle.net/ar2fzbys/

**Comment by pawelgrzybek** [comment]
I'm so sorry but this example is a mess. In your script you reference DOM Nodes that don't exist, you use zepto / jQuery syntax without injecting it to a snippet. There is so many things that prevent this code from working, and non of the errors come from Siema.

Please have a look again at Siema's CodePen collection - there is bunch of examples that provide you a copy / paste solution for majority of popular use cases. If you still struggle, have a look at the the plugin source code which is full of comments for better understanding / contributing reasons.

[CodePen collection](http://codepen.io/collection/Adpkkd/)

**Comment by ilyagru** [comment]
Check one more time please. I simplified more. https://jsfiddle.net/ar2fzbys/4/ At the top of js section I inserted minified Siema script (because there is no cdn for it) and at the bottom there is a needed script. It should change from "Project 1" to "Project 2" when clicking "Button 2" and so on. But there is an error in the console when clicking.

**Comment by pawelgrzybek** [comment]
https://jsfiddle.net/ar2fzbys/6/

Make sure that you use the latest version of Siema. Another thing - don't edit prototype if your navigation leans on independent DOM elements, not programatically generated pagination as I presented on CodePen example.

Works like a charm now :)

**Comment by pawelgrzybek** [comment]
Personally I wouldn't recommend disabling dragging / swiping. These are very intuitive gestures for users nowadays and disabling it may be considered as an anti pattern.

**Comment by ilyagru** [comment]
It works finally. I think the problem was in the old version of the script.
I have to disable dragging here because it is a special case.
Bardzo dziękuję!
One more question please: is it possible to easily create a vertical slider with an additional large photo with the help of Siema?
Like this?
<img width="428" alt="screen shot 2016-12-21 at 01 07 33" src="https://cloud.githubusercontent.com/assets/18074511/21369869/12bc1368-c71a-11e6-8dda-2f75192b92bc.png">

**Comment by pawelgrzybek** [comment]
Answer for this question would be the same as previously. Possible but overkill. Better grab a plugin that offers it out of the box.

**Comment by ilyagru** [comment]
Oh, okay. Thank you for your help and good luck!
