### ISSUE TITLE
Feature request: slide count

### ISSUE THREAD

**Issue by liranh85** [pawelgrzybek/siema#184]
It would be very helpful if Siema had a `slideCount` property or if the API had a `getSlideCount()` method. Would it be possible to add this in?

Thanks!

**Comment by kaigon** [comment]
You can actually do this yourself via the `onInit` function. 

    onInit: function(){
      this.slideCount = this.innerElements.length;
    }

Then you can reference it just like you would `currentSlide`.
https://codepen.io/jparks/pen/eKjXBP

**Comment by pawelgrzybek** [comment]
Hi.

Thanks to @kaigon — this is exactlly what I would do @liranh85. The `innerElements.length` is everything that you need.

Thanks 👋
