### ISSUE TITLE
Feature Request: momentum sliding option

### ISSUE THREAD

**Issue by KevinDrongowski** [pawelgrzybek/siema#185]
I'd like to have an option to allow the user to flick the slider and have it continue sliding, similar to how scrolling works on mobile devices.

**Comment by smartbadger** [comment]
@KevinDrongowski, I was actually about to submit the same feature request! I've forked Siema and have been working on a more natural sliding effect.  You can check out this code pen to see it in action.

https://codepen.io/connorbailes/pen/oypGLY

**Comment by pawelgrzybek** [comment]
Hi.

Next to tons of other cool things this is a plan for 2.0 that is in progress. I will totally ditch the current system of sliding by applying real physics to it. It will be fun but you will have to wait for it.

@smartbadger is see what you are doing on your fork. Cool stuff! Would you like to join me and help me on Siema 2.0? I am the creator and still the only maintainer of Siema.

Have a lovely weekend pals

**Comment by smartbadger** [comment]
Hi @pawelgrzybek, 

Yea that would be awesome! I have a few ongoing projects but I'd love to help out where I can. Let me know any areas that need focus and I'll take a look. 

Thanks!

**Comment by creativecat** [comment]
Will there be an update soon? I totally love your pretty simple script! I tried using Flickity (as I'd like to have the option freeScroll), but it doesn't work as simple as your script and I wasn't able to add it to an existing website :-(

**Comment by smartbadger** [comment]
Hi @creativecat, 

I'm not exactly sure about when the next update will be released. Until then, you can use the npm module of Siema with momentum if you'd like. I created it for the website I work on. https://www.npmjs.com/package/momentum-siema
