### ISSUE TITLE
Carousel with next/prev images in bleed

### ISSUE THREAD

**Issue by dragontennis** [pawelgrzybek/siema#19]
Hey Pawel, I love the simplicity of the carousel you coded. But I have one question/feature request:

Is it possible to use your carousel to create a view, where I see the next/prev images left and right in bleed and the active image always in center. I think it's a variation of showing 3 images per page but only showing the image in the middle in full.

I have an example attached to show you better what I mean:
![screen shot 2016-12-20 at 18 29 11](https://cloud.githubusercontent.com/assets/5261762/21361066/af225a7e-c6e2-11e6-8a27-fb2f5bb9e16c.png)

Thank you very much for your answer in advance.

Best reagards
Chris

**Comment by pawelgrzybek** [comment]
Hi.

Good and bad news here.

Good: Your design is looking very cool.

Bad: As I mentioned in documentation, the only reason why I managed to keep Siema very lightweight is fact that it is built with around 200 lines of code. It comes with few methods and properties exposed in prototype, but it doesn't cover every use case :( Of course it would be possible to "adjust" Siema to do it, but it won't be "lightweight and simple plugin" anymore.

I can recommend you an amazing plugin - [Flickity by David DeSandro](http://flickity.metafizzy.co/) that includes much more methods and porperties. It allows you to control the position of carousel items and margin between them.

Sorry for bad news.

**Comment by dragontennis** [comment]
Thank you very much for your fast answer. I expected that answer. Flickity is looking exactly what I'm looking for.

**Comment by AlecRust** [comment]
@pawelgrzybek can I confirm there is no support for margins between items in siema?

**Comment by pawelgrzybek** [comment]
Correct. You can add paddings inside the items that are inside carousel container, but itself doesn't provide an options for margins.
