### ISSUE TITLE
First and last slides not behaving when loop is enabled

### ISSUE THREAD

**Issue by aubrielee** [pawelgrzybek/siema#190]
Hi Pawel,

I'm trying to make a portfolio website where each slide fades in when it enters, then fades out when it leaves. My solution is to have all slides start at opacity 0, then give it a class with opacity 1 when it's the active slide. This almost works, but I'm having problems with the first and last slides (I'm calling them the "bookend" slides):

1. When going from slide 0 to slide 1, slide 0 doesn't fade out; it remains opaque.
2. When going from slide 3 to slide 0, slide 3 disappears with no transition.
3. When going from slide 0 to slide 3, slide 0 disappears with no transition.

https://codepen.io/aubrie/pen/oyVZXP

I believe this might have something to do with fact that nodes are cloned when loop is enabled. Do you know how I might get my first and last slides to behave like the other slides?

Thank you!
Aubrie

**Comment by pawelgrzybek** [comment]
Hi.

Yeas you are right, this is related with cloned elements that need to be added on front of the array and on the end of it. In this case there is not much that you can do about it :( I would suggest removing `loop` option to keep it simple and make the transition working.

Hopefully it helped you out and thanks for using Siema 👋
