### ISSUE TITLE
Lazy load options 

### ISSUE THREAD

**Issue by gurmeetsinghmalhotra** [pawelgrzybek/siema#194]
Can we have lazy load optins 
 - both if the images in slider are loaded using <img /> tag or used as bg image using css

**Comment by pawelgrzybek** [comment]
Hi.

This is a simple carousel API and adding this feature would make it much bigger. I am not planing to add this feature. It would be helpful only for images but it is not made to work ONLY with images. You can put into Siema whatever you want. Another reason — you can build it yourself using Siemas API.

Thanks and have a great day 👋
