### ISSUE TITLE
Issue when slider is hidden by default and revealed later on some event

### ISSUE THREAD

**Issue by gurmeetsinghmalhotra** [pawelgrzybek/siema#196]
I have 2 sliders on my page and I want to toggle between them on button click such that only one of them is visible at a time. Moreover, I am creating them at once using for loop.

https://codepen.io/gurmet0533/pen/bjWYgP

But there is some display and width issue with the hidden slider. Any help on this will be appreciated.

**Comment by gurmeetsinghmalhotra** [comment]
Any update on this?

**Comment by pawelgrzybek** [comment]
Hi.

When Siema is initialised, it takes some measurements from the DOM. Because your instance is hidden it cannot grab these values. You have to explicitly trigger `init()` when it is revealed.

Thanks and have a nice day 👋
