### ISSUE TITLE
When resizing window and using buttons that are created dynamically with prototype, the buttons disappear

### ISSUE THREAD

**Issue by jstgermain** [pawelgrzybek/siema#200]
Instead of creating buttons with prototype, I have added a wrapper and added the buttons back the normal way. I used prototype to figure out which carousel the buttons belong to when clicking the navigation instead... feel free to use this. This also allows for multiple carousels. https://codepen.io/jstgermain/pen/bjxGQP

**Comment by pawelgrzybek** [comment]
Hi.

It is expected because Siema rebuilds its markup every single time resize is executed. You have to re-add it on resize.

Thanks and have a great day

**Comment by IsidoreIsou** [comment]
Hey,
Sorry but I can't find how to 

> re-add it on resize

Each time I scale or zoom the browser, the buttons disappear.
Thanks !

**Comment by jstgermain** [comment]
> Hey,
> Sorry but I can't find how to
> 
> > re-add it on resize
> 
> Each time I scale or zoom the browser, the buttons disappear.
> Thanks !

See my codepen above. That is why I suggested the edit that @IsidoreIsou denied and closed. I still had to do what I suggested above, so give that a try. :)

**Comment by IsidoreIsou** [comment]
I really can't figure that out... 
What I don't understand is that when I browser scale on the siema homepage for an example, it does not brake anything. I think there is a problem in my code? Here it is, thanks for any help!

```
<script>

  // Because this is possible
  // It doesn't mean that this is a best solution
  // This is a case when you may look at some more complex tools
  // Like very cool Flickity or Swiper
  const siemas = document.querySelectorAll('.siema');

  // Extend prototype with method that adds arrows to DOM
  // Style the arrows with CSS or JS — up to you mate
  Siema.prototype.addArrows = function() {

    // make buttons & append them inside Siema's container
    this.prevArrow = document.createElement('button');
    this.nextArrow = document.createElement('button');
    this.prevArrow.textContent = '';
    this.nextArrow.textContent = '';
    this.selector.appendChild(this.prevArrow)
    this.selector.appendChild(this.nextArrow)

    // event handlers on buttons
    this.prevArrow.addEventListener('click', () => this.prev());
    this.nextArrow.addEventListener('click', () => this.next());
  }

  // this is fairly new way of looping through DOM Elements
  // More about ithere: https://pawelgrzybek.com/loop-through-a-collection-of-dom-elements/
  // For better compatibility I suggest using for loop
  for(const siema of siemas) {
    const instance = new Siema({

      selector: siema,
      draggable: false,
      loop: false,
    });
    instance.addArrows();
  }

</script>
```

**Comment by IsidoreIsou** [comment]
UPDATE:
Ok, I've just understood that it's because I use the [https://codepen.io/pawelgrzybek/pen/yVxmEp](add arrows navigation to prototype) that it brokes on scale or resize. I'm slow.

Still figuring out how to solve it. Will update if success.

**Comment by doughballs** [comment]
This is total pain in the ass. Anyone have a nice solution?

**Comment by panoply** [comment]
This one is not very difficult to apply. It is merely a matter of CSS styles. You need only wrap the slider itself in a `relative` container and then you can assert arrow/chevrons accordingly, here is a quick SCSS snippet:

```scss

.siema-class-name {
	position: relative;

	.prev {
		left: 0px;
	}

	.next {
		right: 0px;
	}

	.prev,
	.next {
		position: absolute;
		height: 100%;
		top: 0;
		bottom: 0;
		z-index: 100;

		&:hover {
			.icon {
				opacity: 1;
			}
		}

		.icon {
			width: 14px;
			height: auto;
			opacity: 0.75;
		}
	}
}
```

When it comes to toggling the visibility of the buttons, the `onChange` hook binds Siemas scope so you can access slides from `this` scope and then from here determine which slide that is active and based on some conditions show/hide the arrows.
