### ISSUE TITLE
Bug when the plugin initializes with many itens

### ISSUE THREAD

**Issue by pedrosouza18** [pawelgrzybek/siema#208]
When I create a div with two columns, one contains the siema with many itens, for example, 30 itens, and another a element, the main div with size 100%, I put in siema configuration which must appears 3 slides for example, but when the plugin initializes appears the next element after 3 first slides, but when I open the inspector after the plugin initialized, the component render right.
- - -

CodePen collection: https://codepen.io/pedrosouza9/pen/qMZwLe

- - -

**Comment by pawelgrzybek** [comment]
Hi.

Sorry, but I am unable to replicate. It is not the case for me and everything is working exactly as expected for me.

![screenflow](https://user-images.githubusercontent.com/3697104/44681084-77861800-aa37-11e8-8ec2-6fb167dd37b9.gif)

**Comment by pedrosouza18** [comment]
I think that this problem is just windows.
![gif](https://user-images.githubusercontent.com/22863027/44683007-60393180-aa1b-11e8-98ac-c3f5824bc91d.gif)
