### ISSUE TITLE
Emoji causes issues in CMS

### ISSUE THREAD

**Issue by MartinP-C** [pawelgrzybek/siema#209]
The emoji cause issues when using Siema in a third-party's CMS.
The script was included on the page (because of a change to fix [#205](https://github.com/pawelgrzybek/siema/issues/205)), but the unicode character "😭" was causing errors within the CMS (I believe because of some encoding configuration the third-party had made). After removing these there were no problems.

Although it is not as nice an experience for developers using Siema, it may be better to have these removed for better compatibility.

**Comment by pawelgrzybek** [comment]
Hi.

Siema doesn't care what kind of content is inside a container. Emojis, photos, videos — doesn't matter. This must be related with some specific CMS that you use.

Thanks and have a great day :)

**Comment by MartinP-C** [comment]
Apologies, I should have clarified.
Emoji in the actual Siema code e.g.: https://github.com/pawelgrzybek/siema/blob/master/src/siema.js#L18

Because the third-party does not allow externally hosted scripts we have to include Siema on the page as a script tag. It then errors on saving the page because of the emoji.
