### ISSUE TITLE
Where is the update() method?

### ISSUE THREAD

**Issue by chadsteele** [pawelgrzybek/siema#210]
I'm looking for the update() method described in this thread...
https://github.com/pawelgrzybek/siema/issues/26#issuecomment-273894670

or perhaps a way to implement it.

**Comment by pawelgrzybek** [comment]
I'm waiting for you PR that creates an alias of `update()` method to `buildSliderFrame()`.

Don't expect. Contribute and appreciate that people give you a tons of great open source for free.

**Comment by chadsteele** [comment]
I'm sorry if I said something offensive.  I just couldn't find it.  I'll look into buildSliderFrame()  thank you

**Comment by chadsteele** [comment]
I'm new to react, etc.  It seems that siema is only useful if the slides are static in a react site since siema will modify the dom in ways that will break react should react want to render again.  Yes?

**Comment by pawelgrzybek** [comment]
Siema is written in very vanilla DOM way. It is not made to work with React out of the box, but it should be fairly easy to write a wrapper for it.

Thanks

**Comment by chadsteele** [comment]
Just an fyi... Perhaps someone will come along who is more skilled than I at React, but as far as I can tell the advantage of React is that you can have a data driven dynamic site (load more slides, etc.) and it doesn't like it if you change the dom for a component that it created since it diffs the dom against it's virtual dom.  I've been trying to create an "infinite slide" with siema in React.  After failing miserably, I tried using jQuery to clone the slides outside of the hidden React's component and then manage that with siema, but that fails too if you want React to manage most of your page... and binding React events to raw javascript events is a challenge as well.  Giving up.  Thanks though.  I'll keep it in mind for other projects though.  I believe it is a great project.  :)

**Comment by tmchng** [comment]
@chadsteele I also needed a infinite carousel with dynamically generated slides, and I did it like this:

https://codepen.io/tmchng/pen/oaEYzB

To update the carousel contents, you can either re-render the carousel items using ReactDom.render, or somehow have the carousel items update itself, which should be trivial.

The only problem is that inserting items will cut off the sliding animation, so I had to do a `setTimeout()` after `onChange()` to account for the animation duration. I haven't look at Siema's source code in detail, but maybe this is something that we can optimize? @pawelgrzybek

**Comment by johannesjo** [comment]
What works for me is just calling  the `resizeHandler()` method.
