### ISSUE TITLE
Image glitch on responsive

### ISSUE THREAD

**Issue by jllagerberg** [pawelgrzybek/siema#218]
So I have been trying to fix this for days. The images glitch between images on responsive.

I am using the latest Firefox.
I have tried with different images.
I have tried with images with the same sizes.
It works while resizing browser, but not if you refresh while being on a smaller window.

![untitled](https://user-images.githubusercontent.com/27690759/46136754-9c44f980-c248-11e8-9a68-405a744db3d5.jpg)

Here is the JSFiddle:
https://jsfiddle.net/5ex40Lho/6/

**Comment by pawelgrzybek** [comment]
It is not a glitch. it inherits transition duration from a parent. If you want to get rid of it, simply remove transition from frame on resize.

Thanks

**Comment by jllagerberg** [comment]
I am trying to understand your answer, but I don't get it. What transition are we talking about here?

And remove transition from frame on resize? Can you give an example?

**Comment by jllagerberg** [comment]
I mean, I even find this in your own codepens. So it can't be intended for it to look like this, right?

https://codepen.io/pawelgrzybek/pen/qrEXbg

![untitled](https://user-images.githubusercontent.com/27690759/46148372-38cac400-c268-11e8-940b-a2f8b7749312.jpg)
