### ISSUE TITLE
Consider a separate file for some inline CSS

### ISSUE THREAD

**Issue by gausarts** [pawelgrzybek/siema#22]
I love your implementation to keep the library lean. Thank you.

I have a small feature request, hopefully this is not against your direction. ;)
The request is to agree on Brad Frost's ;)

IMHO, the library can move some non-critical inline CSS rules out into either a separate CSS file, or some recommended CSS rules via prerequisite CSS rules, similar to how you recommended the HTML structures.

For better wordings and example, please see [lory](https://github.com/meandmax/lory).

The following I noticed can be moved out:
Siema selector: ``` overflow: hidden; ```
Slide item: ``` float: left;```
And also cursor stuffs.

This is just an idea, the actual implementation is up to your preference.
```
.siema {
  overflow: hidden;
  position: relative;
}

.siema .siema__slide {
  float: left;
}

/** Draggable. */
/** is-draggable can be either set by library, or left to users. */
.siema.is-draggable > div {
  cursor: -webkit-grab;
  cursor: grab;
}

/** > DIV is targetting sliderFrame when being pressed down and dragged/swiped. */
.siema.is-draggable > div:active {
  cursor: -webkit-grabbing;
  cursor: grabbing;
}

```
Hopefully it helps trim out some lines, if not adding more ;)
What do you think? Thanks.

UPDATED: To not add new class "is-pointerdown".

**Comment by pawelgrzybek** [comment]
Hi I considered this strategy as one of very early drafts of Siema. I decided to go with inline styles to give users more flexibility. Your solutions is nice and neat but requires user to use naming for classes predefined in the plugin. Now Siema gives a bit more freedom by giving an option to customise a parent selector.
