### ISSUE TITLE
CodePen collection - arrows/dots navigation issues

### ISSUE THREAD

**Issue by euene** [pawelgrzybek/siema#221]
First of all, thank you for creating the fastest and leanest carousel plug-in around. 

I've noticed some minor issues with a few of the CodePens that extend the base plug-in with some extra navigation with buttons/dots.

**1. Arrows (prev/next) navigation CodePen:**

https://codepen.io/pawelgrzybek/pen/yVxmEp

When the viewport is resized, the buttons disappear - they're removed from the DOM completely, perhaps due to Siema resetting the container's defaults and removing elements when recalculating widths?

**2. Dots CodePen:**

https://codepen.io/pawelgrzybek/pen/boQQWy

It seems to have some issues with the perPage and loop settings.

Example test case:
https://codepen.io/anon/pen/BPwQRQ

- When both perPage is showing multiple slides and loop is set to true, the active state won't be applied to the last few dots/slides but everything otherwise works OK.
- When there is just the perPage setting but no loop, the last dots/slides are unreachable.

**Comment by pawelgrzybek** [comment]
Hi.

1. It pagination needs to be recreated onResize as well. This is just an example and inspiration of implementation.

2. Another example. If you use custom pagination that is not part of api you need to add a little bit of logic to cover few more edge cased. This is just an example.

Thanks
