### ISSUE TITLE
Loop producing more elements than intended

### ISSUE THREAD

**Issue by StefanDeGraaf** [pawelgrzybek/siema#222]
The slider is very great and works like a charm in Wordpress, but there is one tiny problem.

I have a WP_Query that loads the 6 most recent posts. I'm currently showing 3 on the page and you have to press a button to go to the next one. As you can imagine the titles of those posts are longer than other post titles. I've made a rather longer than necessary piece of javascript code that get's the ID of those 6 elements (in a foreach loop with a counter and at the end do ++) so the ID is post-title-[counter_number]. However the slides produce 12 elements. So the ID's get messed up. And because of that the initial three get calculated right, but the rest doesn't. I suspect that it has something to do with displaying duplicate's instead of single's.

If I remove the loop option everything works fine, but if I do that I want people to be able to press next en return to the first three instead of doing nothing. (I currently have no clue on how to do this).

I'm fine with turning loop off but then I need that function that takes me back to the first, and if I press previous I want to be taken to the last 3.

**Comment by pawelgrzybek** [comment]
Hi.

I get what your issue is about. You are right, loop function clones slider elements — it is necesary to make it work. I would suggest turning this option off when you use ids and add a bit of logic to slider (of last, go to first, if first go to last). Hopefully that helps.

Have a nice day.
