### ISSUE TITLE
Uncaught ReferenceError: Siema is not defined

### ISSUE THREAD

**Issue by Sleeper18** [pawelgrzybek/siema#225]
The min.js file works but I want to use js file instead so I can make some custom handlers/edits.

<script type="module" src="js/siema.js"></script>
<script type="text/javascript">
   new Siema();
</script>

Uncaught ReferenceError: Siema is not defined

The js module is clearly located above the new Siema() call in my file.

Why could this be happening?

**Comment by pawelgrzybek** [comment]
Hi.

Siema is built by Webpack and exported as UMD (Universal module definition). To make it work you dont need `type="module"` and everything is going to work just fine :)

Thanks
