### ISSUE TITLE
Add init() to API documentation

### ISSUE THREAD

**Issue by mprofitl** [pawelgrzybek/siema#228]
I suggest to add the init() method to the API documentation.

**Comment by Manyaka** [comment]
May be you looking this: https://codepen.io/pawelgrzybek/pen/BRBjpE?editors=1111

**Comment by mprofitl** [comment]
I had found the example but felt it was not linked on from the Github page. I'm not sure anymore. Anyway, it's there, it's linked – thank you very much!
