### ISSUE TITLE
Problem with data-attributes and Loop Function

### ISSUE THREAD

**Issue by kamilczujowski** [pawelgrzybek/siema#231]
Hey,

I already use the slider in some of my projects and I'm very happy.
Currently I have extended the slider so that I can control the slides by page using data attributes. Everything seems to be fine until I want to set the loop function to "true" - then the slider plays crazy and all slides disappear as soon as you click on "Slide-Next".
I have attached a CodePen - maybe I overlooked something or gave it wrong?

https://codepen.io/kamil/pen/OoBYQZ

**Comment by kamilczujowski** [comment]
No idea? Sorry to bother you, but I've tried everything.

**Comment by schrittweiter-dk** [comment]
I got the same problem, and found a solution.
You've to cast your data-attr as integer.

```
const mySiema = document.querySelectorAll('.siema'); 
for(const siema of mySiema) { 
	new Siema({ 
		selector: siema,
		duration: parseInt(siema.dataset.autoplaySpeed),
		loop: true,
		perPage: {
			960: (typeof siema.dataset.mediumItems == "undefined" ? parseInt(siema.dataset.items) : parseInt(siema.dataset.mediumItems)),
			1200: (typeof siema.dataset.largeItems == "undefined" ? parseInt(siema.dataset.items) : parseInt(siema.dataset.largeItems)),
			1600: (typeof siema.dataset.xlargeItems == "undefined" ? parseInt(siema.dataset.items) : parseInt(siema.dataset.xlargeItems)),
		},
	})
}; 
```
