### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by Klynger** [pawelgrzybek/siema#233]
Is there any way to make it look better in SSR? Right now if I put all the elements inside the Siema element it just render all elements, and then when the script is ready is fix it, but this is not good :disappointed:. Do you guys have any plans at giving more support for SSR?

**Comment by pawelgrzybek** [comment]
Hi.

"Do you guys..." — No. It is just me, all by myself. Your situation makes sense, SSR is able just to pre-render stuff, but it doesn't have access to DOM that is needed for Siema to work and look correctly. You can hide it and then rebuild it on `document.load` but it is more like a trick to avoid flesh than solution.

I am not working on this project anymore and I wont drop any new features to Siema.

Thanks for using it anyway. Have a great day 👋
