### ISSUE TITLE
Slider completely lost on window resize

### ISSUE THREAD

**Issue by hafizovic** [pawelgrzybek/siema#234]
Hello. first of all, thanks for great plugin...

Issue I have is that slider gets completely lost on window resize. I tested in Firefox and Chrome. 

Im providing short video with detailed explanation of problem 
https://www.dropbox.com/s/i7y5ufkl96l0yd8/Aqua%20Balkan%20_%20O%20nama%20-%20Mozilla%20Firefox%2012_14_2018%201_49_02%20AM.mp4?dl=0

I also tried to create isolated case on codePen and somehow it works.
I tried to disable all other JS stuff and CSS localy, but still doesn't work.

I will also provide another demo link on page that Im developing http://tvoj.website/konjic/o-nama

CodePen isolated case https://codepen.io/Hafizovic/pen/ebJyea

Thanks in advance

**Comment by pawelgrzybek** [comment]
Hi.

It is hard to say, but my first suspect would be a function that manipulated an "auto-height" of your container. I may be wrong tho. If you can replicate your example 1 to 1 on CodePen I can be more helpful.

Thanks for using Siema 👋
