### ISSUE TITLE
Dragging images with Links

### ISSUE THREAD

**Issue by xinxilas** [pawelgrzybek/siema#236]
For hours i was trying to fix it, i read all issues, abou dragging links problems, and fixes, i see the history about the builds improving it, but even with newer versions i still have the problem 

So just now i discovered the biggest problem is link with images!

`<a href="./"><img src="https://pawelgrzybek.com/siema/assets/siema--yellow.svg" alt="Siema image" /></a>`

And now developer just 4 days ago discontinued the project :(

So anybody has any tip how i fix it?

**Comment by pawelgrzybek** [comment]
Hi, I am the developer who discontinued the project :)

The easies solution for your issue would be:

```css
img {
  pointer-events: none;
}
```

Hopefully it helps. Have a great day 👋

**Comment by x0nium** [comment]
Hi.
Unfortunately this does not solve the problem. It completely disables link on image also when not dragging the slider.
