### ISSUE TITLE
currentSlide value becomes decimal value (e.g. 2.5) when perPage set to 1.5

### ISSUE THREAD

**Issue by princehorn** [pawelgrzybek/siema#238]
Hi Pawel,

to achieve that one and a half slide is in the view port, I set `perPage: 1.5` in my Siema config. This leads to a wrong calculation of `currentSlide` as soon as the last slide is reached (e.g. `2.5` for slide 4). When moving through previous slides, currentSlides remains a double value till first slide is reached.

[This CodePen demonstrates the problem](https://codepen.io/princehorn/pen/dwKJov).

**Comment by pawelgrzybek** [comment]
Hi.

When I built Siema I have never considered a situation to show a fraction on an item. You may fork Siema and change the logic of `next()` / `prev()` method. Should be fairly easy. Unfortunately I discontinued working on this project.

Thanks 👋
