### ISSUE TITLE
While I was trying to create a wordpress plugin with siema this error popping up.

### ISSUE THREAD

**Issue by MahbbRah** [pawelgrzybek/siema#24]
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at new t (siema.min.js?ver=1.1:1)
    at (index):56

**Comment by pawelgrzybek** [comment]
Can you replicate the bug on CodePen please? When you create is as a plugin to Wordpress make sure that the script is injected after a markup (ideally just before closing body tag).

There is nothing better for me to help you with your problem than replicated bug on Codepen, JSfiddle, JSbin, whatever...

**Comment by MahbbRah** [comment]
Sorry But I called the activation on header so that it wasn't working. But with curiosity I called it on footer it's worked ! 

Thank you for a good creation : +1:

**Comment by pawelgrzybek** [comment]
No worries. When the plugin is ready would you like to share it with community? I can add it to "Other implementations" section when it's ready...

https://pawelgrzybek.com/siema/#other-implementations

**Comment by MahbbRah** [comment]
Of course Okay. I will submit a link here.
