### ISSUE TITLE
A way to init and stop the slider

### ISSUE THREAD

**Issue by thijs3dhubs** [pawelgrzybek/siema#245]
Hi,

I'm using the slider a lot, but i now got a design where i need the slider to work on mobiel and to don't show on desktop. On the desktop you should just see the slides in a grid. Is it possible to return to the normal layout when you go from mobile to desktop(From slider to non slider)?

**Comment by pawelgrzybek** [comment]
Hi.

If you are planning to use the same resources for grid / mobile view, the best bet are old simple css media queries.

Thanks for using Siema, have a nice weekend 👋
