### ISSUE TITLE
Sliding on click

### ISSUE THREAD

**Issue by scrgb** [pawelgrzybek/siema#249]
Hello there,

I would like to be able to slide the images when clicking on them instead of dragging or using buttons. 

I bet everything happens here:

```
// make buttons & append them inside Siema's container
  this.prevArrow = document.createElement('button');
  this.nextArrow = document.createElement('button');
  this.selector.appendChild(this.prevArrow)
  this.selector.appendChild(this.nextArrow)
  
  // event handlers on buttons
  this.nextArrow.addEventListener('click', () => this.next());
}
```

Is there any way to reach that?
Thanks in advance, keep the good work!

**Comment by pawelgrzybek** [comment]
Hi. Sure ! Just add event listeners to image. I.e.

```
document.querySelector('#myImage').addEventListener('click', () => this.next());
```

Have a great day :)

**Comment by scrgb** [comment]
Hi. Thanks, it works!
The only problem is that it's affecting all the sliders in my page.

I supposed I should change to .querySelectorAll but it doesn't work.
