### ISSUE TITLE
Update package.json main entry

### ISSUE THREAD

**Issue by mrdbarker** [pawelgrzybek/siema#25]
Siema's package.json file specifies `src/siema.js` as the main entry point. I am excluding transpilation of code in the `node_modules` folder and so `src/siema.js` is not being transpiled to ES*. This means that when I import Siema, the code that is written in ES6 is not transpiled down and the plugin fails in IE and Firefox.

The package.json main entry point should be changed to `dist/siema.min.js`.

Happy to PR.

**Comment by pawelgrzybek** [comment]
Great suggestion!

**Comment by pawelgrzybek** [comment]
Thats done, please update Siema via npm. Everything should be working great now. Sorry for that and thanks for contribution!

**Comment by mrdbarker** [comment]
Perfect, thanks @pawelgrzybek - quick response and fix 🥇
