### ISSUE TITLE
Load siema in a non-visible DOM element 

### ISSUE THREAD

**Issue by arielconti10** [pawelgrzybek/siema#255]
I want to put siema inside a element that isn't visible when DOM loads, like a modal or something like that. 
When I tried to do this, Siema loads but with width and height 0. 
Can anyone help me with this ? 

Thanks a lot.

**Comment by pawelgrzybek** [comment]
I am afraid it is impossible to do something like that. You need to re-initialise the `init()` method when element becomes visible. If the element is hidden it is not able to render the element in memory and determine the size.
