### ISSUE TITLE
Taking over maintenance

### ISSUE THREAD

**Issue by BatuhanW** [pawelgrzybek/siema#258]
Hi,

Thanks for the great project! We've been using this library for our micro apps and it works really nice even on low-end devices. As @pankod, We'd like to migrate this project to typescript and take over the maintenance. You can communicate with me through batuhan@pankod.com.

Have a nice day!

**Comment by pawelgrzybek** [comment]
Hi.

I promise I will come back to this project very soon. I will prioritise TypeScripting this library and fix some critical bugs.

Thanks for contribution. I would really love to see some projects where you used Siema on production 🥑

**Comment by BatuhanW** [comment]
Good to hear!

We are using it for the micro apps we are creating for a signage network, so we don't have url to show it. And usually these apps has 2-3 days lifespan. Since these apps run on webos 2/3 and chrome 38, siema works really nice on limited resources.

**Comment by barroudjo** [comment]
Hello,
I wanted to say thank you as well, great library, not only is it easy to use, it is also very lightweight.
If maintenance can be ensured this is great news !

**Comment by croban** [comment]
> Hi.
> 
> I promise I will come back to this project very soon. I will prioritise TypeScripting this library and fix some critical bugs.
> 
> Thanks for contribution. I would really love to see some projects where you used Siema on production

You can see it here
https://sbi.expert/

**Comment by tan-ahmed** [comment]
any updates on what's happening?
