### ISSUE TITLE
Slides don't work in Chrome Android with jekyll

### ISSUE THREAD

**Issue by S-B99** [pawelgrzybek/siema#264]
Android 10 (Build QQ1A)
Chrome 79
- - -

Pen: https://codepen.io/s-b99/pen/oNgKLqY
Pen works fine on desktop and mobile.
- - -

Issue: when deploying with jekyll it seems to bork on chrome android. 
![](https://imgur.com/C10Yxvc.png)

Here is my code:
```html
---
layout: default
title: Gallery
---

## owo 

<head>
  <link rel="stylesheet" href="/assets/css/gallery.css">
</head>
<body>
<div class="siema">
    <div><img src="https://pawelgrzybek.com/siema/assets/siema--pink.svg" alt="Siema image" /></div>
    <div><img src="https://pawelgrzybek.com/siema/assets/siema--yellow.svg" alt="Siema image" /></div>
    <div><img src="https://pawelgrzybek.com/siema/assets/siema--pink.svg" alt="Siema image" /></div>
    <div><img src="https://pawelgrzybek.com/siema/assets/siema--yellow.svg" alt="Siema image" /></div>
    <div><img src="https://pawelgrzybek.com/siema/assets/siema--pink.svg" alt="Siema image" /></div>
    <div><img src="https://pawelgrzybek.com/siema/assets/siema--yellow.svg" alt="Siema image" /></div>
    <div><img src="https://pawelgrzybek.com/siema/assets/siema--pink.svg" alt="Siema image" /></div>
    <div><img src="https://pawelgrzybek.com/siema/assets/siema--yellow.svg" alt="Siema image" /></div>
</div>

<script async src="/assets/siema.min.js"></script>
<script>
    const mySiema = new Siema({
          loop: true,
          easing: 'cubic-bezier(.17,.67,.32,1.34)',
          duration: 200,
          onChange: () => {
            setTimeout(() => { mySiema.next(1); }, 2000);
          },
    });

    mySiema.next(1);

</script>
</body>

```
```css
---
---

body {
  width: 100%;
  margin: 0 auto;
}

img {
  width: 100%;
}

.siema {
  margin: 1rem 0;
}
```

- - -

The website is very similar to this repo here, with different pages:
https://github.com/S-B99/kamibluewebsite

**Comment by S-B99** [comment]
It seems to be acting as if my onChange was 
```html
            setTimeout(mySiema.next(1),) 4000;
```
instead of
```html
            setTimeout(() => { mySiema.next(1); }, 2000);
```

**Comment by S-B99** [comment]
Confirmed in Firefox as well :/

**Comment by pawelgrzybek** [comment]
Hi.

Siema has nothing to do with Jekyll. It just outputs HTML on the end of the day. Without looking at your particular example it is very hard to help you. CodePen link attached works just fine to me. Either zip your whole thing and send it over of recreate the problem on CodePen please.

**Comment by S-B99** [comment]
Hi, I have made a repo with usage instructions for testing here: https://github.com/S-B99/webzipped

You can view the page here: https://s-b99.github.io/webzipped/p/gallery.html

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17222512/73610347-1d7e7000-45a4-11ea-992f-4ae4282ac079.gif)
![](https://imgur.com/JEwukcN.jpg)

**Comment by S-B99** [comment]
I forgot to mention, codepen works fine for me on desktop and mobile. The site works fine in mobile view on a laptop with firefox debugging. It only breaks when it's used on a real device.

**Comment by pawelgrzybek** [comment]
Oooo I see where the issue is now :)

By doing this:

```js
const mySiema = new Siema({
          loop: true,
          easing: 'cubic-bezier(.17,.67,.32,1.34)',
          duration: 200,
          onChange: () => {
            setTimeout(() => { mySiema.next(1); }, 2000);
          },
    });

    mySiema.next(1);
```

on every change, you instantiate a new setTimeout. In result there is many timers running on the background. Somehing that you want to do looks more like:

```
const mySiema = new Siema({
      loop: true,
      easing: 'cubic-bezier(.17,.67,.32,1.34)',
      duration: 200
});

setTimeout(() => mySiema.next(), 2000);
```

With this you end up having one timer only. It should fix your issues. Have a good day :)

**Comment by S-B99** [comment]
I tried this before, and I copy pasted your code to be sure. This only runs once unfortunately, on a page refresh.

**Comment by S-B99** [comment]
Also double checked, and the issue you see in the screenshots still happens on mobile. I'll update the testing repo in a minute

**Comment by pawelgrzybek** [comment]
Instead of using `setTimeout` use `setInterval` ;) Then it will trigger `next()` method every 2 seconds not only just once.

**Comment by S-B99** [comment]
That doesn't solve my issue. It's still broken on mobile, as showed in the screenshots I sent above

**Comment by pawelgrzybek** [comment]
Could you replicate this mobile situation on CodePen please?

**Comment by S-B99** [comment]
I can not, no. I don't think this is a siema issue, it appears to not load the js on mobile at all. Thanks for the help however c:

**Comment by S-B99** [comment]
It was the async tag breaking it <3
