### ISSUE TITLE
PerPage not working with flex boxes

### ISSUE THREAD

**Issue by simplenotezy** [pawelgrzybek/siema#265]
Hey - I've adjusted your "per page" codepen a bit. All I did was to implement bulma and their "columns". When using columns it doesn't seem to work: https://codepen.io/simplenotezy/pen/NWqqwYR

I am not sure why, as I'm not really a pro frontender...

**Comment by pawelgrzybek** [comment]
Hi.

Your CSS framework added some styling that prevent Siema from working correctly. Siema to work needs just a bit of styling on main container. If you want to add some styling please, add styling to individual carousel items, not to the main container. The class `columns` produces an error in your example :( 

Hopefully that helps. Have a great day 🥑

**Comment by simplenotezy** [comment]
@pawelgrzybek the solution is simple.

Put: "display: block" on .column
