### ISSUE TITLE
Heavily nested divs - is this normal behavior?

### ISSUE THREAD

**Issue by simplenotezy** [pawelgrzybek/siema#266]
I'm not sure if I initiate the slider in a wrong way, or if this is normal behavior, but I notice all theese nested elements if I inspect the slider. Is this normal behavior?

![image](https://user-images.githubusercontent.com/3786627/74861707-1482f200-534b-11ea-89a6-8200af55abd4.png)

If I don't initiate Siema my divs look like this:

![image](https://user-images.githubusercontent.com/3786627/74861965-878c6880-534b-11ea-84ac-16ee78f8abb8.png)

**Comment by pawelgrzybek** [comment]
This is 100% expected.

This extra markup is needed for Siema to work correctly. It applies position, transition and hides elements outside of a wrapper. 

Hopefully that helps 👋

**Comment by simplenotezy** [comment]
thanks a ton!
