### ISSUE TITLE
Delaying Autoplay

### ISSUE THREAD

**Issue by mrerickdavid** [pawelgrzybek/siema#270]
I have a page where I set a 6s delay to autoscroll to the main content, which includes a Siema slider. I set Siema to autoplay slides and change them every 250ms. The problem is, when the page scrolls to the content, 6 seconds in, Siema has already played a couple slides.

I’d like to start the autoplay to either when Siema is in the page, or after a 6s delay. How can I achieve that?

Here is my whole Siema code.

```
function printSlideIndexWithIndicator() {
    let currentSlide = this.currentSlide;
    let currentSelector = document.querySelector('.siema-current');
    let totalSelector = document.querySelector('.siema-total');
    if (currentSlide < 0) {
       currentSelector.innerHTML = this.innerElements.length + currentSlide + 1;
    } else {
        currentSelector.innerHTML = this.currentSlide + 1;
    }
    totalSelector.innerHTML = this.innerElements.length;
}
const mySiema = new Siema({
    duration: 250,
    loop: true,
    easing: "cubic-bezier(.42,0,.58,1)",
    onInit: printSlideIndexWithIndicator,
    onChange: printSlideIndexWithIndicator,
});

const myInterval = setInterval(() => mySiema.next(), 3000);

document.querySelector(".siema-prev").addEventListener("click", () => {
    mySiema.prev();
    clearInterval(myInterval);
});
document.querySelector(".siema-next").addEventListener("click", () => {
    mySiema.next();
    clearInterval(myInterval);
});
document.querySelector(".siema").addEventListener("mousedown", () => {
    clearInterval(myInterval);
});
document.querySelector(".siema").addEventListener("touchstart", () => {
    clearInterval(myInterval);
});
```

**Comment by devdavi** [comment]
You should be able to do this with javascript, not necessarily a function of siema. Use setTimeout() to fire a function that contains your setInterval so that it delays before starting the auto-rotate. I haven't tested this with your buttons, so there could be some errors, but if you still need it I can set up a codepen example that works later. 

`
var delayAutoRotate = function(){
    const myInterval = setInterval(() => mySiema.next(), 3000);
}

setTimeout(delayAutoRotate, 6000);
`

**Comment by mrerickdavid** [comment]
That worked great! Thank you!
