### ISSUE TITLE
How get pagination dots with active one?

### ISSUE THREAD

**Issue by minaminfo** [pawelgrzybek/siema#272]
I've checked all of the examples but I couldn't find the example with dots navigation. Anyhow, I could use pagination number method but how can I get the current active one?

**Comment by jm-via** [comment]
You can use the `currentSlide` method to get the active slide. Building on the pagination example provided, you can then use this to set the correct button to "active." See: https://codepen.io/jm-via/pen/NWGYPwN

**Comment by pawelgrzybek** [comment]
Thanks for answering and contribution @jm-via.
