### ISSUE TITLE
Siema js link is broken on codepen 

### ISSUE THREAD

**Issue by samoel02** [pawelgrzybek/siema#276]
Hi,
I was browsing siema examples on codepen, but all of them are broken do to siema core js link. 
I hope you update the link and thank you for creating this.

**Comment by pawelgrzybek** [comment]
Uuuu damn! My fault, I removed some redirects yesterday. I will fix it now!
Thanks a ton @samoel02 !

**Comment by pawelgrzybek** [comment]
It should be fixed now.
Thanks a lot for reporting and sorry for the downtime!

Have a great Sunday!

**Comment by samoel02** [comment]
Thank you
