### ISSUE TITLE
Fade or fadeIn/fadeOut

### ISSUE THREAD

**Issue by netlarico** [pawelgrzybek/siema#278]
Hello, nice slide carousel, i want to implement, but i see that has 'ease-out' option only, How can i set up with fade-in and fade-out or 'fade' mode, is it possible?
many thanks

**Comment by pawelgrzybek** [comment]
Sorry, this more is not possible and won't be. Fade transitions are very easily achievable using few lines of JavaScript — carousel library would be an overkill for this. Sorry @netlarico :(
