### ISSUE TITLE
What's a loop in video?

### ISSUE THREAD

**Issue by AnotherAnkor** [pawelgrzybek/siema#32]
Hi!
Awesome stuff. Thanks =)
But what's a loop you are used in video for demo site?

**Comment by pawelgrzybek** [comment]
Hi, thanks 😃

Sorry what do you mean by loop? There isn't any loop at the video mate.

**Comment by AnotherAnkor** [comment]
I mean music. Usually it's named "loop".

**Comment by pawelgrzybek** [comment]
Hahaha. It's Github, I related word "loop" with programming loop, sorry :)

There you go my friend: https://audiojungle.net/item/positive-ukulele/19053043

Have a great day.
