### ISSUE TITLE
Get index of the current active slide while dragging or swiping between the slides

### ISSUE THREAD

**Issue by DxF5H** [pawelgrzybek/siema#35]
Hi!

I get the index of the current active slide with `currentSlide` and prev / next buttons. Can I also get the index of the current active slide while I drag or swipe between the slides?

Thanks in advance!

**Comment by pawelgrzybek** [comment]
Hi.

Unfortunately something like this isn't possible at this moment and I'm not planing to add something like this anytime soon. It would be very resource heavy to check for position on slide / swipe. It recalculates `currentSlide`on the end of transition between slides. 

What is your use case if I can ask? Have a great day 😉
