### ISSUE TITLE
Use Siema in Alux Framework

### ISSUE THREAD

**Issue by afmarchetti** [pawelgrzybek/siema#36]
Hi i'm Andrea, Siema is fantastic compliments!
Can i use Siema i my CSS/HTML Framework?
https://github.com/afmarchetti/alux
I will put all the necessary credits to your github page ;-)

Many thanks!

**Comment by pawelgrzybek** [comment]
Sure thing :)

Will be nice if you just keep an info about the author (myself).
I'm really glad that you like Siema :)

✋
