### ISSUE TITLE
Blurry slides

### ISSUE THREAD

**Issue by runepiper** [pawelgrzybek/siema#38]
Sometimes the slides a blurry, because the widths and transforms are a bit too precise. I suggest to round them.
It is the `div` created by Siema.

```
width: 455.188px;
transform: translate3d(-227.594px, 0px, 0px);
```

I'm using Chrome 56 on macOS

**Comment by malteriechmann** [comment]
Any news?

**Comment by pawelgrzybek** [comment]
Hi.

Just released a one update that fixes few issues. This one will be fixed in the next one. Sorry guys for postponing. It should be released in few days.

Have a great day you all 👾

**Comment by malteriechmann** [comment]
Thanks!

**Comment by pawelgrzybek** [comment]
Hi @runepiper and @malteriechmann.

I spent some time looking at this issue and there is no way that I can replicate this bug. Any chance to create a CodePen / JSFiddle, JSbin example for me please? If you can provide an info about the browser that the issue occurs it would be really fantastic. 

Looking forward to have some info back as I'm really keen to investigate further before next big release. Thanks

**Comment by runepiper** [comment]
Hey @pawelgrzybek

Sure, take a look at [www.actio.de](http://www.actio.de). At the top right is a small slider and some of the slides are blurry because of the described bug / feature.

**Comment by pawelgrzybek** [comment]
Amazing example! Thanks a ton! if you can give me an info about OS and browser and it's version. Now I have a perfect reference and example to investigate. It will be fixed in next minor release @runepiper.

Ps. Nice looking website 👌

Thanks you again.

**Comment by runepiper** [comment]
Yeah sure. I'm using Safari 10.1 on macOS 10.12.4.

Thanks 🙂

**Comment by pawelgrzybek** [comment]
Hi guys.

Just to let you know that issue has been resolved. As correctly suggested if was related with pixel rounding. This is everything that was needed to resolve this issue :)

https://github.com/pawelgrzybek/siema/commit/ec54570fd430acacbfcd6ccf1bbb967f1f71eb62#diff-0f98adb017f3c5a836cd2a762834f5b9

Thanks again for reporting and have a great weekend 🍻

**Comment by malteriechmann** [comment]
Thanks!

**Comment by pawelgrzybek** [comment]
Actually thats better :)

https://github.com/pawelgrzybek/siema/commit/2b568f3822b2debffe1b58d5961e9be7c497a286#diff-0f98adb017f3c5a836cd2a762834f5b9

**Comment by runepiper** [comment]
Well done!
Have a nice weekend as well and happy easter holidays 🥚 🐰

**Comment by tyftler** [comment]
Since I still had issues with missing rounding I created another pull request to fix this: https://github.com/pawelgrzybek/siema/pull/178

**Comment by euene** [comment]
I was also having issues with blurry slides but tyftler's pull request fixed it for me. Will #178 be merged into the next release?
