### ISSUE TITLE
Unnecessary item wrapping?

### ISSUE THREAD

**Issue by AlecRust** [pawelgrzybek/siema#39]
A wrapping `<div>` is added to each item in the carousel, so:

```html
<div style="float: left; width: 16.6667%;">
  <div class="carousel-item">
    carousel item
  </div>
</div>
<div style="float: left; width: 16.6667%;">
  <div class="carousel-item">
    carousel item
  </div>
</div>
```

Instead of adding the inline styles to the existing children:

```html
<div class="carousel-item" style="float: left; width: 16.6667%;">
  carousel item
</div>
<div class="carousel-item" style="float: left; width: 16.6667%;">
  carousel item
</div>
```

As far as I can tell, this means equal margins around items (https://github.com/pawelgrzybek/siema/issues/19) can't be achieved with CSS. I was going to do something like this:

```css
.carousel-item:nth-child(odd) {
  padding-right: 5px;
}

.carousel-item:nth-child(even) {
  padding-left: 5px;
}
```

To achieve this:

![screenshot](https://i.imgur.com/3hCHQpe.png)

Are these wrappers necessary i.e. could the inline styles be added to the existing children instead to ease styling?

And/or maybe siema could add a class to the current far right carousel item so the [excess padding](https://i.imgur.com/68voGfB.png) could be removed with CSS. The `:nth-child` approach I mention above can get out of hand quickly, especially with a [responsive](http://codepen.io/pawelgrzybek/pen/LbgoVK) slider.

**Comment by pawelgrzybek** [comment]
Hi.

I added the additional wrapper `div` in the recent update to Siema 1.2.0. https://github.com/pawelgrzybek/siema/releases/tag/v.1.2.0

It allows to add paddings to carousel elements even without `box-sizing: border-box`. As we for some users it is helpful, for another it may cause some issues. Sorry about it. As I said in docs, it meant to be simple solution but unfortunately it doesn't cover all scenario. You may try other more powerful libraries like Flickity instead.

Have a look at the example, is it something that you after?
http://codepen.io/pawelgrzybek/pen/gmPmrq

Thanks for reporting...

**Comment by AlecRust** [comment]
My apologies, I didn't see that pen in the collection. Using margin on left and right of each item instead of the padding I had around the entire carousel works well actually - thank you!

**Comment by pawelgrzybek** [comment]
You haven't seen this pen in collection because I created it for you 5 min ago :)

Enjoy :)
