### ISSUE TITLE
Slide multiple items

### ISSUE THREAD

**Issue by AlecRust** [pawelgrzybek/siema#40]
When there's more than one item in a visible carousel, the pagination buttons still only shift the carousel by one item at a time:

http://codepen.io/pawelgrzybek/pen/womzxN

Does Siema support shifting all the visible items at one time, rather than just shifting by one?

**Comment by pawelgrzybek** [comment]
Hi @AlecRust.

This is a feature that I added recently in Siema 1.2.0.

Instead of:

```
prev.addEventListener('click', () => mySiema.prev());
next.addEventListener('click', () => mySiema.next());
```

Pass an optional arguments to `prev()` and `next()` methods. Like so...

```
prev.addEventListener('click', () => mySiema.prev(2));
next.addEventListener('click', () => mySiema.next(2));
```

:-)

**Comment by AlecRust** [comment]
Oh great, thanks! I don't suppose this will work with the responsive solution though:

http://codepen.io/pawelgrzybek/pen/LbgoVK

Could change the value passed in there based on screen size I guess.

**Comment by pawelgrzybek** [comment]
Of course it is possible :)

```js
const mySiema = new Siema({
  perPage: {
    768: 2,
    1024: 3,
  },
});

function checkHowMany() {
  const windowWidth = window.innerWidth;
  if (windowWidth > 1024) {
    return 3;
  }
  else if (windowWidth > 768) {
    return 2;
  }
  else {
    return 1;
  }
}

const prev = document.querySelector('.prev');
const next = document.querySelector('.next');

prev.addEventListener('click', () => mySiema.prev(checkHowMany()));
next.addEventListener('click', () => mySiema.next(checkHowMany()));

console.log(mySiema)
```

**Comment by pawelgrzybek** [comment]
This is one of the possible solutions. Works great :)

**Comment by AlecRust** [comment]
Fair enough, thank you :)
