### ISSUE TITLE
Fraction pagination

### ISSUE THREAD

**Issue by AlecRust** [pawelgrzybek/siema#41]
Is there an easy way to achieve fraction pagination indicators in Siema?

![screenshot](https://i.imgur.com/h9hWQ43.png)

If there were 2 slides visible, it would say 2/10.

**Comment by pawelgrzybek** [comment]
Hi.

Of course it is possible. It is not the cleanest solution but works like a charm. Next time just log to console the instance of your Siema and have a look what kind of info it gives you in the prototype. You cannot do everything, but you can do a lot by available properties and methods...

http://codepen.io/pawelgrzybek/pen/ryxged

Thanks for using Siema :)

**Comment by pawelgrzybek** [comment]
With callback `onChange` it would be easier, but this isn't possible in current version. ON my roadmap and will be available in next version of Siema...

**Comment by AlecRust** [comment]
Thanks, works well :)
