### ISSUE TITLE
Scrollbar indicator

### ISSUE THREAD

**Issue by AlecRust** [pawelgrzybek/siema#42]
Last one :) if you've got this I don't have to use a different library!

Is a scrollbar indicator possible with Siema to show progress?

![screenshot](https://i.imgur.com/lS2NK3A.png)

**Comment by pawelgrzybek** [comment]
It is not available on Siema and I'm not planing to introduce this feature at all. Swiper does it really well tho. http://idangero.us/swiper/

**Comment by AlecRust** [comment]
That is a shame, I guess I'll have to use swiper :(

**Comment by pawelgrzybek** [comment]
It is not a shame at all. As I said in the docs...

> Siema's purpose is to provide a basic carousel tool and allow developers to extend it by using the available methods. It doesn't come with any complex configuration and myriad options — I would like to keep it this way. If you need a more powerful library I recommend the amazing Flickity by David DeSandro or Swiper by iDangero team.

**Comment by AlecRust** [comment]
It is a shame for me I assure you :) since I'd like to avoid an alternative with complex configuration and myriad of options, and this is the last feature in my way. I understand your point though, that is fair enough 👍 

I'll have a look at solutions to this and add here if I come up with anything that may help others.

**Comment by AlecRust** [comment]
Here is my solution to this, which works with the responsive example though a refresh is needed for each breakpoint:

http://codepen.io/AlecRust/pen/aJZLpq/
