### ISSUE TITLE
Extra column of pixels from previous slide is showing in Safari with even-numbered window width

### ISSUE THREAD

**Issue by jsit** [pawelgrzybek/siema#43]
The example slider on the home page for the project shows a single column of pixels from the previous slide when going to the next slide. This is only happening for me in Safari, and only when the window is an even number of pixels wide. This doesn't happen at all, for instance, in Chrome.

I don't think it's a bug with this library, I think Safari must just be doing the translate3d math not quite precisely, but I wanted to record the problem here in case others are having it.

Screencast here: http://d.pr/v/DhOT

One solution I've found is to add left and right padding to each slide, which prevents this "bleeding".

**Comment by pawelgrzybek** [comment]
Hi Jay.

Thanks for reporting. I knew about some sub-pixel rendering issues but your screencast definately helped. I'll take some time to investigate this problem further and let you know when the fix (if possible) is ready.

Thanks a lot and have a nice day.

**Comment by pawelgrzybek** [comment]
Hi @jsit.

I spent some time looking at this issue and there is no way that I can replicate this bug. Any chance to create a CodePen / JSFiddle, JSbin example for me please? If you can provide an info about the browser that the issue occurs it would be really fantastic. 

Looking forward to have some info back as I'm really keen to investigate further before next big release. Thanks

**Comment by jsit** [comment]
Thanks @pawelgrzybek. I'm also not able to reproduce it in Safari 10.1 on my work MacBook. I'll try again at home (where it was happening) later.

The Siema example page itself was exhibiting this issue, which is why I didn't include a Pen/Fiddle.

**Comment by pawelgrzybek** [comment]
Hi @jsit 

Just to let you know that issue has been resolved. It was related with pixel rounding. This is everything that was needed to resolve this issue :)

https://github.com/pawelgrzybek/siema/commit/ec54570fd430acacbfcd6ccf1bbb967f1f71eb62#diff-0f98adb017f3c5a836cd2a762834f5b9

Thanks again for reporting and have a great weekend 🍻

**Comment by pawelgrzybek** [comment]
Actually thats better :)

https://github.com/pawelgrzybek/siema/commit/2b568f3822b2debffe1b58d5961e9be7c497a286#diff-0f98adb017f3c5a836cd2a762834f5b9

**Comment by jsit** [comment]
Thanks! 👍
