### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Loruz** [pawelgrzybek/siema#44]
Hi, Siema is a great tool. But is it possible to add a infinite loop of elements , and not (as it is now) rewinding back loop ? Thanks. :)

**Comment by pawelgrzybek** [comment]
Hi.

It is not possible at this moment. Personally I consider this functionality as an anti pattern as user cannot clearly spot the gat after last slide. I'm happy with current functionality and I'm not planning to add infinite loop anytime soon. Sorry :(

Have a great day.

**Comment by raglannyc** [comment]
I disagree that it's an anti-pattern. I don't think most users care whether they are on the first or last or seventh slide, the number of the slide doesn't matter. And it's usually pretty obvious when you've looped around since you're seeing things you've seen before. I'd like to see infinite loop as an option, if it doesn't add too many Kb to the script :)

**Comment by pawelgrzybek** [comment]
@raglannyc be assured that the one is coming. It is a high priority feature on my list — straight after RTL support.

Have a great day 🥑

**Comment by benjibee** [comment]
Any progress on this, or v1.5 for that matter? I'd love very much to see this as I have a large full-screen slider and the quick-whip back to the beginning is almost dizzying! Thanks 👍

**Comment by tommymarshall** [comment]
Very dizzying. I'm open to working on it, but don't want to double up on the effort.

**Comment by pawelgrzybek** [comment]
This feature is in progress and definitely it is coming to Siema @tommymarshall :)

**Comment by benjibee** [comment]
@pawelgrzybek just tested it out and pushed it live, it works like a charm. Thank you for this update! 🎉

**Comment by pawelgrzybek** [comment]
I will be very thankful to see some Siema example on lie projects! I'm glad that you like it! Enjoy using Siema :)

**Comment by benjibee** [comment]
@pawelgrzybek sure, it's a client's photography website called [the Independent Photographer](https://independent-photo.com/), I'm still switching over all of the sliders to Siema (still can't get it centered) but it's already been a huge improvement over other solutions 👍

**Comment by aczekajski** [comment]
@benjibee If you want to center your Siema slider, you might be interested in this: https://github.com/pawelgrzybek/siema/pull/121 - just look at the first comment with styles and the code in the last one.

**Comment by pawelgrzybek** [comment]
Hi @benjibee @aczekajski 

Siema has never been designed to work in centered mode. At this stage it requires a big changes in generated markup and API unfortunately. The solution that I suggested in a #121 is hacky and undocumented, but will do the job as long as you wrap the Siema wrapper in some container with 'overflow: hidden'. Maybe one day in 2.0 — but no earlier than that.

Thanks for feedback.

**Comment by benjibee** [comment]
@pawelgrzybek @aczekajski thanks both for the suggestions. Sadly my images are various widths, I've actually tried something like that example before to no avail. It also doesn't work with this loop, as you can see the DIV being swapped out in a flash. I'll keep tinkering and hope I find a solution!
