### ISSUE TITLE
Responsive breakpoints not working as expected

### ISSUE THREAD

**Issue by raglannyc** [pawelgrzybek/siema#45]
I would expect the `perPage` setting to work the same way media queries do, where it takes effect at that pixel dimension, but instead with Siema it seems to take effect at one pixel greater than the number I set.

With my following code, the slider breaks to 2 slides at 481px wide viewport and it should break at 480px:

`const mySiema = new Siema({
	selector: '#siema',
	perPage: {
		480: 2,
		768: 3,
		993: 5,
		1600: 6,
	},
	loop: true
});`

**Comment by pawelgrzybek** [comment]
Hi.

To mimic the functionality of mq min-width, yeah? Makes sense for me. Would you like to contribute?

https://github.com/pawelgrzybek/siema/blob/master/src/siema.js#L128

Thanks and have a great day 🥑

**Comment by raglannyc** [comment]
I would love to contribute! Tell me what to do

**Comment by pawelgrzybek** [comment]
Your issue has been resolved in 566ee37f825dbd7ef533d19b6d20ee2c68e03253 commit. Thanks anyway :)
