### ISSUE TITLE
Listen for event

### ISSUE THREAD

**Issue by izebb** [pawelgrzybek/siema#5]
I would like to use things like on slide event or init event for an action and also pagination?

**Comment by pawelgrzybek** [comment]
Hi Gabriel.

As mention in the docs, Siema is a very basic solution but with it's own restrictions. It is very lightweight (just 1kb gzipped) plugin, but doesn't come with many methods or callbacks.

I will make sure to cover your request in the future version of documentation and I may consider adding some additional callbacks / methods in the future version of Siema.

> Siema's purpose is to provide a basic carousel tool and allow developers to extend it by using the available methods. It doesn't come with any complex configuration and myriad options — I would like to keep it this way. If you need a more powerful library I recommend the amazing [Flickity](http://flickity.metafizzy.co/) by David DeSandro or [Swiper](http://idangero.us/swiper/) by iDangero team.
