### ISSUE TITLE
Gulp Webapp and Siema is not defined ESLint

### ISSUE THREAD

**Issue by halol** [pawelgrzybek/siema#50]
Hey, I tried to find any solution but no luck...
While using Yo Gulp Webapp generator I'm trying to build my static website but I got the errors
```
  45:2   error  Do not use 'new' for side effects  no-new
  45:6   error  "Siema" is not defined             no-undef
```
It's compiling `plugins.js` with bootstrap's plugins and Siema.js at the end of the file (so it's ok).
But I have `new Siema()` included under `main.js` file which is below everything else and it still can't recognise it.

Any advice?

**Comment by pawelgrzybek** [comment]
Hi.

Siema internally is using standard UMD (Universal Module Definition) pattern boilerplate. This is a well standardised and considered as a best practice way of building scripts at the moment.

Output of your error looks like ESLint error and it is nothing related with plugin by itself. You need to configure your dev environment to handle this situation. I'm afraid that there is not much that I can help you with here... Sorry.

Thanks
