### ISSUE TITLE
goTo function doesn't trigger onChange event

### ISSUE THREAD

**Issue by brandon-pereira** [pawelgrzybek/siema#52]
When triggering goTo it should fire the onChange callback passed in. 

http://codepen.io/branclon/pen/MmJZpg?editors=1111

**Comment by brandon-pereira** [comment]
Pull request created here: https://github.com/pawelgrzybek/siema/pull/53

**Comment by pawelgrzybek** [comment]
Wow!

Top dude! Let me just give it a quick review this evening and merge.

Thanks a ton 🍻

**Comment by pawelgrzybek** [comment]
Callback on CodePen examples works as expected now. Thanks again dude!
