### ISSUE TITLE
Fade animation and free mode

### ISSUE THREAD

**Issue by exdeniz** [pawelgrzybek/siema#54]
I don't found solution for fade animation, for example on desktop fade animation and mobile swipe animation.
About Free mode, on swipe mobile free mode like scroll.

perPage: 'auto' possible?

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for reporting. I have never considered adding 'fade' effect to Siema. I'm sorry but I consider this as an anti-pattern. This functionality is way more than I ever expected from very tiny and simple Siema's class.

For free mode you actually don't need a carousel as it can be easily achieved with pure CSS.

```js
perPage: 'auto'
```

What would this do? Personally I prefer the explicit sizes and slide number as it is and I believe that majority of users prefer to control it by themselves too. What the logic behind `auto` should be?

Thanks and have a great day 🥑

**Comment by exdeniz** [comment]
```
perPage: 'auto'
```
For responsive carousel and random width slide.

On other issues, the position is clear.

**Comment by pawelgrzybek** [comment]
Is there any other carousel plugin that uses this randomness? I need to see the example to understand it.

**Comment by exdeniz** [comment]
http://idangero.us/swiper/demos/06-slides-per-view-auto.html

**Comment by pawelgrzybek** [comment]
Aaa ok I get it. Nope, it is not possible to do on Siema. Sorry about it. It generates markup / styles that make every inner item equal width.
