### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by m-kr** [pawelgrzybek/siema#60]
First of all, the plugin is great, very lightweight with friendly API. I had to resign from using it in my company project, because of missing infinite loop mode. Back to the begin of items list is very ugly. I think that many users could have similar fellings.

**Comment by m-kr** [comment]
I've found your answer in #44, so I close the issue.

**Comment by pawelgrzybek** [comment]
It is second thing on my priority list straight after RTL support now. Ill drop this feature soon. Thanks again for opening and closing an issue :)

Have a great day and thanks for a kind words about the script 🍻

**Comment by pawelgrzybek** [comment]
Hi.

Feature that you requested has been merged with master branch and it i ready to use.

https://codepen.io/pawelgrzybek/pen/zwOrKN

Thanks again for using Siema 👋

**Comment by m-kr** [comment]
@pawelgrzybek works like a charm, now Siema hasn't any competition 😄

**Comment by pawelgrzybek** [comment]
Thanks a ton @m-kr 

Ill be thankful to see Siema on some live examples!

Thanks again for using Siema and have a great evening 👋
