### ISSUE TITLE
Create tags for recent releases

### ISSUE THREAD

**Issue by roberthl** [pawelgrzybek/siema#62]
Thank you for this awesome package, it's a real pleasure to work with!

I see in npm the latest release is marked as 1.4.6, but the JS package manager I'm using relies on the tags in GitHub and currently the latest there is 1.4.2.  Please would you be able to create tags for the most recent versions in Git?

**Comment by pawelgrzybek** [comment]
I promise I will do :) It is just my lazy lifestyle. It will change as I like Siema same as you do :*
