### ISSUE TITLE
Options for disabling prev and next buttons

### ISSUE THREAD

**Issue by mattjared** [pawelgrzybek/siema#68]
Thanks for the work on Siema!! Really enjoying the lightweight, no dependency solution.

I like the solution for infinite looping submitted in #58. While that's still in the works I wanted to disable and enable previous or next buttons (or hide and remove arrows) if it's the first or last slide. In the pen below you can see I target the `siema` element and count it's children and subtract by 1 to get the number of slides in the carousel. From there, if the `currentSlide` equals the modified number I just grabbed right before matches and then disable the "next" option in this case. In production I might use an arrow or some other indicator but either way I want to dynamically know when I'm on the last slide. 

https://codepen.io/matt_jared/pen/proYVr

My question: Is there a better way to do this? There will have to be even more conditional logic if the number of slides visible changes at multiple viewports. If #58 is going to be merged in somewhat soon this might not be necessary but I feel like being able to disable / enable the last element a little more elegantly than what I'm capable of might be a nice option as a Codepen example even for folks in the future. Thanks for your time! =]

**Comment by jabyess** [comment]
I second this idea, with an additional caveat:

I noticed that the `currentSlide` property doesn't seem to reflect the right value if the `perPage` setting is anything other than 1. For example, if i have 6 slides, and `perPage` set to 3, the `currentSlide` value increases past 3.

I forked the codepen @mattjared wrote and updated it:

https://codepen.io/jabyess/pen/mMWEZe

There is a problem with figuring out the use case for this. What should the currentIndex value be when there are multiple slides in view? Should it be the middle? First? last?

**Comment by goodguyry** [comment]
If you're only showing one slide at a time, you can do something like this in your `onChange` function:

```javascript
const index = mySiema.currentSlide;
prev.disabled = (0 === index);
next.disabled = (index + 1 === mySiema.innerElements.length);
```

This is what I've done in the past, and I've found it works great. But I just hit the `perPage` issue @jabyess mentioned so I'm kinda stuck...

The only fix I can think of is to move forward/backward by the `perPage` amount, then check for how near the `currentSlide` is to the end.

https://codepen.io/GoodGuyRy/pen/xXZPYa

**Comment by pawelgrzybek** [comment]
Hi guys.

Catching up with all the issues and preparing for next release of Siema very soon.

@mattjared unfortunately #58 won't be merged because it solved one issue but introuduced number of bugs with other parts on Siema API. You don't have to worry, infinite looping is coming :) To answer your question, the solution presented by @goodguyry is exactly what I would do. For example:

https://codepen.io/pawelgrzybek/pen/boQQWy

Thank you all for using Siema and massive support whenever I don't have a time to assist. You are legends people 🥑
