### ISSUE TITLE
Margins between elements

### ISSUE THREAD

**Issue by maugelves** [pawelgrzybek/siema#70]
Hi Pawel, do you have an example on how to give some margins between the items?
Thank you!
Mauricio

**Comment by pawelgrzybek** [comment]
Hi.

This feature will come with new version of Siema but there is a hack to do it with paddings around slider items and negative margins around slider by itself.

Sorry about it...

**Comment by jimblue** [comment]
Any update about this feature?

**Comment by pawelgrzybek** [comment]
Nope. I will release a patch (possibly today) that fixes number of bugs. This feature wont be included in this release. It is coming with a coming minor update tho.

**Comment by jimblue** [comment]
ok great, thanks for your fast answer @pawelgrzybek 😄  !

**Comment by pawelgrzybek** [comment]
No worries! Thanks for your contribution and using Siema!

**Comment by smichaelsen** [comment]
It's not yet in, is it?

**Comment by riiccardo** [comment]
omfg

**Comment by kgoedecke** [comment]
@pawelgrzybek any updates here, if not whats the hack that you suggested?
