### ISSUE TITLE
Lighthouse reports possible improvement

### ISSUE THREAD

**Issue by matt3224** [pawelgrzybek/siema#72]
![screen shot 2017-08-07 at 2 39 15 pm](https://user-images.githubusercontent.com/2401925/29029060-48e735bc-7b7e-11e7-8adc-953bcae62c80.png)
Lighthouse reporting this, is this something that can be adjusted in siema?

**Comment by pawelgrzybek** [comment]
Hi.

Please consider to update Siema. All listeners in current version are passive and you shouldn't get this one with the latest version of Siema @matt3224 

Thanks

![passive](https://user-images.githubusercontent.com/3697104/29029484-b362b55a-7b7f-11e7-8033-038dbc6c8b81.jpg)

**Comment by matt3224** [comment]
Thats great, isn't working for me though. Check it out [http://next.thechemistrygroup.com/](http://next.thechemistrygroup.com/)

**Comment by phunkb** [comment]
@pawelgrzybek sorry to bring this up, im getting this on v1.5.1 now.

**Comment by tomrutgers** [comment]
I'm experiencing this issue with `siema@^1.5.1`

<img width="705" alt="Schermafbeelding 2020-01-06 om 21 27 28" src="https://user-images.githubusercontent.com/6247534/71846693-76ed9f00-30cb-11ea-9a56-3c6a66b5255b.png">

**Comment by pawelgrzybek** [comment]
Yeah, there is  a PR for it and most likely it is going to be merged soon.
