### ISSUE TITLE
Feature Request: Centered Slides

### ISSUE THREAD

**Issue by Daniel-Karlsson** [pawelgrzybek/siema#75]
First of all I would like to thank you for such a great job on the project!

I would be thankful if we you had the possibility to add cented slides function as idangerous swiper  http://idangero.us/swiper/demos/07-centered.html

Best regards,
Daniel

**Comment by imlinus** [comment]
+1, this is a function that could be well needed

**Comment by WhereJuly** [comment]
Hi Daniel, just curious, what do you mean by centered slides?
You can center any Siema slide or a group of them using CSS without any change to Siema. Can you describe in more details?

**Comment by pawelgrzybek** [comment]
Hi all.

I like the centered option for Swiper. it is working really cool and looking good! Unfortunately Siema is much simpler library and the main purpose that it suits it to provide a basic API for a carousel that spans the whole container width.

To create centered slides a'la Swiper — tracking position & width of each slide is required. This one requires a huge extension to current Siema codebase that I'm not ready for and don't want to do. Main purpose of my Siema is to give you guys a basic API and you can do with this shit what you want. If API restricts you, jump on project like Swiper of Flickity with much richer list of methods and properties. These are amazing libraries!

Thanks a ton.

**Comment by jamestomasino** [comment]
```css
.siema > div > div {
  display: flex;
  justify-content: center;
}
```

This works pretty well for me. The surrounding divs are still float: left, but this will center your content inside that. In my case they're just images. If you have more complex slides you may need a bit more.
