### ISSUE TITLE
Feature Request: removeAll

### ISSUE THREAD

**Issue by RafaelC457ro** [pawelgrzybek/siema#78]
One function really useful could be `removeAll()`, just like `remove()`, but for remove all elements, like a reset. expect to be:
```js
const MySiema = Siema()
const img = document.createElement('img')

img.src =  'some url'
MySiema.append(img)

MySiema.removeAll()
````

Thanks!

**Comment by pawelgrzybek** [comment]
Hi.

Could you give me an example why would you like to use it? Can you give me a little bit of background please? Personally I cannot think of any practical use case. If I would like to delete something, probably it would be a single item. If not destroy probably can do all I want.

Let me know please as I'm keen to resolve all issues and enhancements.

**Comment by RafaelC457ro** [comment]
Hi, I use that in image gallery carousel, and sometimes images need to be updated, and there not another way to do, except clean everything and insert new images again. So I find this temporary
solution: 
````js
const siema = new Siema()
const count = siema.innerElements.length

 if (count > 0){
   for (var i = count; i >= 0 ; i--){
       siema.remove(i);
    }
 }
// insert new images
````
will be nice if has `removeAll()` function, and I don't need to iterate over inner elements, to remove it. 
Thanks.

**Comment by pawelgrzybek** [comment]
Fair enough!

I will drop `removeAll()` method with next release. Thanks for suggestion again!

**Comment by pawelgrzybek** [comment]
Hi.

I am just finishing a next release. It was a good time for me to review all feature / enhancements requests. The core principle of Siema is to give users enough properties and methods  to accomplish these kind of things via API (your request is a perfect example). Feature that you requested is an edge case and not many users are gonna benefit from added this one to list of methods. Hopefully it makes sense and you get my reasoning why I try to keep API as neat as possible. 

Thanks for using Siema 👋
