### ISSUE TITLE
Fade effect

### ISSUE THREAD

**Issue by TomOne** [pawelgrzybek/siema#79]
Awesome project, thank you 👍

Do you plan to implement an option for a fade effect as transition between the slides?

**Comment by pawelgrzybek** [comment]
Hi.

I don't think it is going to happen. This script provides an easy solution to create a basic touch / drag friendly carousel. Adding"fade" effect requires to massively change a code base witch breaks the core principle of this script — simplicity.

There is plenty of great libs that let you use fade effect. BX Slider is one of my favourite and it is very reliable. Worth to have a look.

Sorry for bad news and have a great day 🥑

**Comment by TomOne** [comment]
I see, thanks for your feedback.
