### ISSUE TITLE
total no of slides

### ISSUE THREAD

**Issue by graforlock** [pawelgrzybek/siema#83]
It would be nice to ada this functionality to the API (i.e. `slideCount`) as the scope of finding the current total number of slides per page is varying per viewport breakpoints. It is sometimes needed for example to disable next/prev buttons out of. 

Without it, the user has to calculate it outside of the API and for example, double up some of the viewport logic.

**Comment by pawelgrzybek** [comment]
Hi.

Great suggestion! For the time being use this...

```js
consy mySiema = new Siema();
const slideCount  = mySiema.innerElements.length;
```

Thanks again and have a great weekend!

**Comment by graforlock** [comment]
Its not really about total number of slide elements but page slides.

If I have 12 slides and go

```javascript 
perPage: {
 0 : 4,
 768: 6,
 1024: 12
}
```

Then its 2 for anything bigger than 768 and 3 for anything below. It'd be good to know that at any given point with unknown/variable number of slides.

**Comment by migueljteixeira** [comment]
@pawelgrzybek can't you accept [my pull request](https://github.com/pawelgrzybek/siema/pull/81)? It solves this issue.
