### ISSUE TITLE
Non-equal cell width

### ISSUE THREAD

**Issue by LeonLiber** [pawelgrzybek/siema#84]
Hello,
I'm trying to implement an image carousel with Siema.
Some of the images are vertical and some horizontal so I've set a `max-height: 200px` on the image inside the cell. 

Unfortunately, since Siema wraps the cells with a fixed percentage width element - the cell takes up more space than necessary.

Is there any way to support "variable" cell widths?

Thanks in advance

**Comment by pawelgrzybek** [comment]
Hi.

Unfortunately the main purpose of Siema is a lightweight solution to create equal width items inside carousel. I'm sorry to say that there is no way to implement a vary width items at this moment. 

Thanks a lot for using Siema.
