### ISSUE TITLE
Image width bug

### ISSUE THREAD

**Issue by sergeyromanovsky** [pawelgrzybek/siema#88]
hi, i have a bug with image width at the right, some px show from next image, help me pls, you made a very nice carousel, i don't want to chage it)
[app.zip](https://github.com/pawelgrzybek/siema/files/1315916/app.zip)

**Comment by pawelgrzybek** [comment]
Hi.

I downloaded your zip file but there is too much going on. Recreate your bug on CodePen please.

Thanks

**Comment by sergeyromanovsky** [comment]
I don't know how to upload image on codepen

ср, 20 сент. 2017 г. в 09:40, Pawel Grzybek <notifications@github.com>:

**Comment by sergeyromanovsky** [comment]
Can we have a Skype call?

ср, 20 сент. 2017 г. в 09:43, Сергей Романовский <s.romanovsky11@gmail.com>:

**Comment by sergeyromanovsky** [comment]
I will share my screen

ср, 20 сент. 2017 г. в 09:54, Сергей Романовский <s.romanovsky11@gmail.com>:

**Comment by pawelgrzybek** [comment]
You cannot upload images on CodePen without pro subscription but you can always use some random image mate. Anything that show the issue. We can have a quick Skype this weekend if you wont manage CodePen example by this time.

Thanks again for raising an issue.

**Comment by sergeyromanovsky** [comment]
i just loaded my site, and anything is fine, maybe this trouble was because
of catch, thank u


2017-09-20 11:35 GMT+03:00 Pawel Grzybek <notifications@github.com>:

**Comment by pawelgrzybek** [comment]
I like this kind of scenarios :) Thanks for fixing your problem by yourself :)

Have a great day 🥑

**Comment by sergeyromanovsky** [comment]
Hi, can u help me pls? I need to make a pagination on slider (I did it from
the example on codepen), when the active slide is different, and i want to
make it using svg line, how can i do it?

2017-09-20 13:54 GMT+03:00 Pawel Grzybek <notifications@github.com>:
