### ISSUE TITLE
Multiple instances on a same page with navigation

### ISSUE THREAD

**Issue by cotumaccio** [pawelgrzybek/siema#89]
Hi, sorry for bothering you. I need to use multiple slides on the same page, and for each slide I need to add navigation with two buttons, prev and next. I have seen from this example "Siema - multiple instances on a same page", which can be run together, okay, but I do not find how to run keystrokes. can you help me? Thank you.

**Comment by pawelgrzybek** [comment]
Hi.

Keystroke will be very tricky as it needs to be assigned to one instance of a carousel. The implementation of this is close to impossible as you have just one left and one right key on the keyboard.

Thanks a lot and have a great day. More than happy to provide a further support.

**Comment by olets** [comment]
Google finds this page and not the pen, so adding that link here — maybe it'll help someone in the future https://codepen.io/pawelgrzybek/pen/JbaELp

**Comment by lelabdigitalfr** [comment]
So much late but you can implement multiple siema/navigation here is my example : 
https://jsfiddle.net/m9752wsd/
If someone drop here can be helpful.
