### ISSUE TITLE
Auto-Start / Rotate

### ISSUE THREAD

**Issue by JaySMa** [pawelgrzybek/siema#9]
Hello..
I like how your slider works, but is there an option for it to do an auto-rotate?

I would like it to continue rotating without needing the prev/next buttons.

Thank you for your time and attention..

**Comment by pawelgrzybek** [comment]
Hi.

Siema doesn't come with many options, but JavaScript can do a lot. Example that you are asking for requires very little of extra code. I created a CodePen example for you and I added it to collection with rest of Siema examples. Have a look...

Siema - autoplay & loop:
http://codepen.io/pawelgrzybek/pen/MbPbLM

Siema - collection on CodePen full of examples:
http://codepen.io/collection/Adpkkd/

Hopefully this helped you out Jay.
Have a great day 😊
