### ISSUE TITLE
Does it really work with RequireJS?

### ISSUE THREAD

**Issue by WhereJuly** [pawelgrzybek/siema#90]
Hello!

This is great piece of code. But it does not work with RequireJS out of box. Looking at the code there is an UMD wrapper footprint at the top of the file seen. Though being requested via `define()` call the code does not return Siema constructor. It just returns `undefined`.
And I cannot use RequireJS shim config as Siema looks like using AMD.
Can you please check if it is possible to make it work with RequireJS?

Thank you.

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for reporting. To be honest with you I have never checked it — just blindly rely on Webpack UMD output. I'll do my investigation and come back with fixed code.

Have a great day @WhereJuly

**Comment by WhereJuly** [comment]
Thanks a lot. That would be a great convenience to be able to include it as AMD.

You too :1st_place_medal:

**Comment by WhereJuly** [comment]
I am establishing the jsFidlle example now just for convenience. Will return shortly.

**Comment by WhereJuly** [comment]
Here it is.
https://jsfiddle.net/Valy/vb90y0tt/21/

**Comment by WhereJuly** [comment]
[Here is the solution](https://github.com/krisk/Fuse/issues/178)
As per the link, I could not re-pack the source with Webpack. I just fixed the point referred in the link manually in the minified file. It works for both Siema and the utility at the links. Hope that helps.

Have nice day @pawelgrzybek and thanks again for the great slider :))

**Comment by tourdefran** [comment]
Since new versions where deployed, I wonder if now it can be used with RequireJs
