### ISSUE TITLE
Please add option for siema plugin such as { wrapAround: true }

### ISSUE THREAD

**Issue by js-digital** [pawelgrzybek/siema#93]
Requirements: 
{ wrapAround: true } wraps cells around to the other end, so you can keep flicking without hitting an end. It should be like infinite scrolling.

Thank you.

**Comment by codyogden** [comment]
This has already been requested in #44. It's on the roadmap.

**Comment by pawelgrzybek** [comment]
Hi.

Feature that you requested has been merged with master branch and it i ready to use.

https://codepen.io/pawelgrzybek/pen/zwOrKN

Thanks again for using Siema 👋
