### ISSUE TITLE
Separate 'draggable' and 'swipe' options

### ISSUE THREAD

**Issue by benjibee** [pawelgrzybek/siema#94]
I'd very much like to enable touch swiping for mobile, but have no use for dragging on desktop, and would prefer it to be disabled.

Looking at the code I'm not 100% sure why these are the same option, I also find _draggable_ to be misleading as it's used to enable touch swiping.

I'd like to suggest `draggable` and `swipable` (or whatever you'd call this!) to be separate config options.

Also, thanks for making the best slider plugin out there! 👏

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for using Siema and really cool suggestion.
I love this kind of issues —  can be solved by one liner :)

```js
const mySiema = new Siema({
  draggable: 'touchstart' in document.documentElement ? true : false,
});
```

This kind of config should do all what you need my friend :)

Thanks again and have a nice day 🥑

**Comment by benjibee** [comment]
Siema,

Thanks for this nifty little one-liner, it does indeed solve my issue. I have to say, however, that I suggested this new option, and made the PR, because I thought that perhaps these two options should not be one in the same.

That being said, if there's something I've missed, or I don't get, then I'll just be on my way. There's plenty of things beyond me, so maybe this is just one of those things… 🤝

**Comment by pawelgrzybek** [comment]
You did amazing job by adding a configuration for both. I may consider to add it in future version of a Siema. For the time being I have to be focued to delived 1.5 with all the goodies that I promised :)

Thanks again for using Siema @benjibee !
