### ISSUE TITLE
[bug]  Next / Prev buttons in modal with Siema work only once

### ISSUE THREAD

**Issue by ChrisPlaneta** [pawelgrzybek/siema#97]
I'm working on a store with "quickview" modal windows that are displayed on category pages. These modals are dynamically generated by ajax and php and contain basic product info and a gallery.

This is what I am doing:
- clicking a "quickview" button
- ajax and php work behind the scene and generate a new modal window with product data and gallery
- after the window is generated a callback function initiates Siema

The problem is that when I close that modal (JS changes its CSS display to "none") and reopen it (CSS display flex), the next and prev buttons won't work.

I've recorded it as a proof. Download vid here > https://www.dropbox.com/s/xaqywfqmemrbhle/Siema-issue.wmv?dl=0

**Comment by ChrisPlaneta** [comment]
I've solved it. Error in my JS. Sorry for the trouble.

**Comment by pawelgrzybek** [comment]
Hi again.

I see the issue. Unfortunately there is not enough of a context to diagnose this issue. Is it possible for you to recreate this issue on CodePen please? It may be related with model box, it may be related with event bubbling / capturing, it may be related with tons of things.

Please provide a little bit more context please.

Thanks 🥑
