### ISSUE TITLE
Option for adding a class to current slide

### ISSUE THREAD

**Issue by mattjared** [pawelgrzybek/siema#98]
I need a class added to each slide to trigger animations inside the slide. I played around with the currentSlide option to create a demo on Codepen...

https://codepen.io/matt_jared/pen/PJadPO

It might be useful to just pass a class to the API for transitions so users could get straight to writing CSS.

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for suggestion. I love the idea but I need to tell you why I won't implement it :)

The core principal of Siema is to give you a basic math, core carousel functionality and powerful API. As long as the functionality can be done in few lines of code (like in your CodePen example) there is no need to add it to lib. If I was implementing all the tiny requested features like yours, this API wouldn't be lightweight anymore. Hopefully my reasoning makes sense to you and you still enjoy using Siema.

This is my version of your functionality:

```js
function printSlideIndex() {
  document.querySelector('.js-index').innerHTML = this.currentSlide;
  
  this.innerElements.forEach((slide, i) => {
    const addOrRemove = i === this.currentSlide ? 'add' : 'remove';
    this.innerElements[i].classList[addOrRemove]('show');
  })
}

const mySiema = new Siema({
  onInit: printSlideIndex,
  onChange: printSlideIndex,
});

const prev = document.querySelector('.prev');
const next = document.querySelector('.next');


prev.addEventListener('click', () => mySiema.prev());
next.addEventListener('click', () => mySiema.next());
```

Have a lovely day 🥑

**Comment by mattjared** [comment]
Totally agree. My example is better for unique cases to not bloat the library. Thanks for making such a cool tool that allows things like this to be slapped on with ease!

**Comment by huvber** [comment]
Does this work with `loop` options? because doesn't seem to work with it

**Comment by frontendpaul** [comment]
Indeed, it doesn't seem to work when `loop` option is enabled.

**Comment by gol4nsky** [comment]
Hi, 

It's any solution to get currentSlide with loop option enabled ?
