### ISSUE TITLE
Feature Request: add ID &/or class to Siema wrapper & class to slider items

### ISSUE THREAD

**Issue by WhereJuly** [pawelgrzybek/siema#99]
Many issues can be solved by the CSS alone. For this some attributes for the Siema wrapper and the items could be great to have.

E.g. 
```
new Siema({
    // ... other config options here
    // For attributes use their DOM names, not HTML ones.
    // Default: all '';
    wrapperAttrs: {id: 'my-wrapper-id', className: 'my-wrapper-class'}, 
    itemClass: 'my-item-class'
});
```
Could be easy to implent but effective when additional styling (centering, paddiing etc.) is needed.

**Comment by pawelgrzybek** [comment]
Sorry.

What is the benefit of doing that from Siema config level over plain html?
What is the difference between code from your example and this…

```html
<div id="my-wrapper-id" class="my-wrapper-class">
  <div class="my-item-class">Something cool here</div>
  <div class="my-item-class">Something cool here</div>
  <div class="my-item-class">Something cool here</div>
</div>
```

```js
new Siema({
  // ... other config options here
  selector: '#my-wrapper-id'
});
```

??

**Comment by WhereJuly** [comment]
When you have to address the Siema genuine wrapper via the CSS you have to do it like this:
```
.my-wrapper-class > div {
// some rules
}
```
For the Siema genuine item the addressing would look like 
```
.my-item-class > div {
// rules here
}
```
Not specific enough though would work.

**Comment by pawelgrzybek** [comment]
I don't think that adding this complexity solves any issue. I don't consider it as an improvement that is worth adding more to the Siema API. Just follow good old CSS practices. Example...

```html
<div class="slider js-slider">
  <div class="slider__item">Some cool stuff</div>
  <div class="slider__item">Some cool stuff</div>
  <div class="slider__item">Some cool stuff</div>
</div>
```

```css
.slider {
  /* some rules */
}

.slider__item {
  /* some rules */
}
```

```js
const mySlider = new Siema({
  selector: '.js-slider'
});
```

KISS!

**Comment by WhereJuly** [comment]
You answered the non-finshed comment:) I sent it before I finished it. Please read the finished one :) Thanks.

**Comment by pawelgrzybek** [comment]
Hi.

Sorry for rapid answer. Actually my previous snippet is still a valid answer. I don't dive an option to add a class / id to this elements because user SHOULDN'T ever manually edit styles of these elements. These elements are created for functionality purpose, not for styling purpose. user should be focused on actual slide styling and all the slide inner elements, not elements generated by library.

Hopefully my reasoning makes sense.

**Comment by WhereJuly** [comment]
No problem. Thanks for the answer. 

I understand your point. 
Just note that some people in the comments asked for centering the slides. Or padding between slides. It is all and many more doable by CSS alone added to the genuine Siema elements by a Siema user. No need in JS in a code base. Just add handles to the Siema elements and a couple of example Pens showing how to use the genuine Siema elements correctly via CSS thus making the slider even more valuable. Just keep it in mind for a future.

**Comment by makis-spy** [comment]
This makes it quite dirty to try and target slides without hardcoding uniq classnames... in loops and dynamic lists what not
